//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
using System.Xml.Serialization;
using System.Collections;

namespace InferMed.MACROBuffer
{

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SubjectData.xsd")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SubjectData.xsd", IsNullable=false)]
	public class MACROSubject 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Visit", Type=typeof(MACROSubjectVisit))]
		public ArrayList Visit = new ArrayList();
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Study;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Site;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Label;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute("Visit", Namespace="http://tempuri.org/SubjectData.xsd")]
	public class MACROSubjectVisit 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Eform",typeof(MACROSubjectVisitEform))]
		public ArrayList Eform=new ArrayList();
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Code;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Cycle;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute("Eform",Namespace="http://tempuri.org/SubjectData.xsd")]
	public class MACROSubjectVisitEform 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Question",typeof(MACROSubjectVisitEformQuestion))]
		public ArrayList Question=new ArrayList();
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Code;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Cycle;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute("Question",Namespace="http://tempuri.org/SubjectData.xsd")]
	public class MACROSubjectVisitEformQuestion 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Code;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Cycle;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Value;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Timezone;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Timestamp;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SubjectData.xsd")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SubjectData.xsd", IsNullable=false)]
	class NewDataSet 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("MACROSubject")]
		public MACROSubject[] Items;
	}
}