CREATE OR REPLACE TRIGGER TR_TRIALSUBJECT_SEQUENCE BEFORE INSERT OR UPDATE OF SUBJECTTIMESTAMP, IMPORTTIMESTAMP, LOCKSTATUS ON TRIALSUBJECT FOR EACH ROW BEGIN SELECT SEQ_SUBJECTDATA.NEXTVAL INTO :NEW.SEQUENCEID FROM DUAL; END;
/
--//--
CREATE OR REPLACE TRIGGER TR_VISITINSTANCE_SEQUENCE BEFORE INSERT OR UPDATE OF VISITDATE, VISITSTATUS, LOCKSTATUS, IMPORTTIMESTAMP ON VISITINSTANCE FOR EACH ROW BEGIN SELECT SEQ_SUBJECTDATA.NEXTVAL INTO :NEW.SEQUENCEID FROM DUAL; END;
/
--//--
CREATE OR REPLACE TRIGGER TR_CRFPAGEINSTANCE_SEQUENCE BEFORE INSERT OR UPDATE OF CRFPAGEDATE, CRFPAGESTATUS, CRFPAGEINSTANCELABEL, LOCKSTATUS, IMPORTTIMESTAMP, LABORATORYCODE ON CRFPAGEINSTANCE FOR EACH ROW BEGIN SELECT SEQ_SUBJECTDATA.NEXTVAL INTO :NEW.SEQUENCEID FROM DUAL; END;
/
--//--
CREATE OR REPLACE TRIGGER TR_DIR_SEQUENCE BEFORE INSERT OR UPDATE OF RESPONSETIMESTAMP, LOCKSTATUS, IMPORTTIMESTAMP ON DATAITEMRESPONSE FOR EACH ROW BEGIN SELECT SEQ_SUBJECTDATA.NEXTVAL INTO :NEW.SEQUENCEID FROM DUAL; END;
/
--//--
CREATE OR REPLACE TRIGGER TR_DIRH_SEQUENCE BEFORE INSERT OR UPDATE ON DATAITEMRESPONSEHISTORY FOR EACH ROW BEGIN SELECT SEQ_SUBJECTDATA.NEXTVAL INTO :NEW.SEQUENCEID FROM DUAL; END;
/
--//--
CREATE OR REPLACE TRIGGER TR_MIMESSAGE_SEQUENCE BEFORE INSERT OR UPDATE ON MIMESSAGE FOR EACH ROW BEGIN SELECT SEQ_SUBJECTDATA.NEXTVAL INTO :NEW.SEQUENCEID FROM DUAL; END;
/
--//--