INSERT INTO MACROControl (MACROVersion,BuildSubVersion,IdleTimeOut) VALUES ('3.0','50',300);

INSERT INTO AutoImportControl (UpLoadOrder,StartStop,WaitInterval) VALUES (1,'START',60);

INSERT INTO ClinicalTrial (ClinicalTrialId,ClinicalTrialName,ClinicalTrialDescription,PhaseId,StatusId) VALUES (0,'Library','Library',1,1);

INSERT INTO DataType (DataTypeId,DataTypeName) VALUES (0,'Text');
INSERT INTO DataType (DataTypeId,DataTypeName) VALUES (1,'Category');
INSERT INTO DataType (DataTypeId,DataTypeName) VALUES (2,'Integer Number');
INSERT INTO DataType (DataTypeId,DataTypeName) VALUES (3,'Real Number');
INSERT INTO DataType (DataTypeId,DataTypeName) VALUES (4,'Date/Time');
INSERT INTO DataType (DataTypeId,DataTypeName) VALUES (5,'Multimedia');
INSERT INTO DataType (DataTypeId,DataTypeName) VALUES (6,'Laboratory Test');

INSERT INTO Keyword (Keyword) VALUES ('ABS');
INSERT INTO Keyword (Keyword) VALUES ('ABSOLUTE');
INSERT INTO Keyword (Keyword) VALUES ('ACCESS');
INSERT INTO Keyword (Keyword) VALUES ('ACTION');
INSERT INTO Keyword (Keyword) VALUES ('ADA');
INSERT INTO Keyword (Keyword) VALUES ('ADD');
INSERT INTO Keyword (Keyword) VALUES ('AFTER');
INSERT INTO Keyword (Keyword) VALUES ('ALL');
INSERT INTO Keyword (Keyword) VALUES ('ALLOCATE');
INSERT INTO Keyword (Keyword) VALUES ('ALTER');
INSERT INTO Keyword (Keyword) VALUES ('AND');
INSERT INTO Keyword (Keyword) VALUES ('ANY');
INSERT INTO Keyword (Keyword) VALUES ('ARE');
INSERT INTO Keyword (Keyword) VALUES ('AS');
INSERT INTO Keyword (Keyword) VALUES ('ASC');
INSERT INTO Keyword (Keyword) VALUES ('ASSERTION');
INSERT INTO Keyword (Keyword) VALUES ('AT');
INSERT INTO Keyword (Keyword) VALUES ('AUDIT');
INSERT INTO Keyword (Keyword) VALUES ('AUTHORIZATION');
INSERT INTO Keyword (Keyword) VALUES ('AUTONUMBER');
INSERT INTO Keyword (Keyword) VALUES ('AVG');
INSERT INTO Keyword (Keyword) VALUES ('AVERAGE');
INSERT INTO Keyword (Keyword) VALUES ('BEFORE');
INSERT INTO Keyword (Keyword) VALUES ('BEGIN');
INSERT INTO Keyword (Keyword) VALUES ('BETWEEN');
INSERT INTO Keyword (Keyword) VALUES ('BIT');
INSERT INTO Keyword (Keyword) VALUES ('BIT_LENGTH');
INSERT INTO Keyword (Keyword) VALUES ('BOTH');
INSERT INTO Keyword (Keyword) VALUES ('BY');
INSERT INTO Keyword (Keyword) VALUES ('BYTE');
INSERT INTO Keyword (Keyword) VALUES ('CASCADE');
INSERT INTO Keyword (Keyword) VALUES ('CASCADED');
INSERT INTO Keyword (Keyword) VALUES ('CASE');
INSERT INTO Keyword (Keyword) VALUES ('CAST');
INSERT INTO Keyword (Keyword) VALUES ('CATALOG');
INSERT INTO Keyword (Keyword) VALUES ('CATEGORY');
INSERT INTO Keyword (Keyword) VALUES ('CHAR');
INSERT INTO Keyword (Keyword) VALUES ('CHAR_LENGTH');
INSERT INTO Keyword (Keyword) VALUES ('CHARACTER');
INSERT INTO Keyword (Keyword) VALUES ('CHARACTER_LENGTH');
INSERT INTO Keyword (Keyword) VALUES ('CHECK');
INSERT INTO Keyword (Keyword) VALUES ('CLINICALTRIALID');
INSERT INTO Keyword (Keyword) VALUES ('CLOSE');
INSERT INTO Keyword (Keyword) VALUES ('CLUSTER');
INSERT INTO Keyword (Keyword) VALUES ('COALESCE');
INSERT INTO Keyword (Keyword) VALUES ('COLLATE');
INSERT INTO Keyword (Keyword) VALUES ('COLLATION');
INSERT INTO Keyword (Keyword) VALUES ('COLUMN');
INSERT INTO Keyword (Keyword) VALUES ('COMMENT');
INSERT INTO Keyword (Keyword) VALUES ('COMMIT');
INSERT INTO Keyword (Keyword) VALUES ('COMPRESS');
INSERT INTO Keyword (Keyword) VALUES ('CONNECT');
INSERT INTO Keyword (Keyword) VALUES ('CONNECTION');
INSERT INTO Keyword (Keyword) VALUES ('CONSTRAINT');
INSERT INTO Keyword (Keyword) VALUES ('CONSTRAINTS');
INSERT INTO Keyword (Keyword) VALUES ('CONTINUE');
INSERT INTO Keyword (Keyword) VALUES ('CONVERT');
INSERT INTO Keyword (Keyword) VALUES ('CORRESPONDING');
INSERT INTO Keyword (Keyword) VALUES ('COUNT');
INSERT INTO Keyword (Keyword) VALUES ('CREATE');
INSERT INTO Keyword (Keyword) VALUES ('CRFPAGECYCLENUMBER');
INSERT INTO Keyword (Keyword) VALUES ('CRFPAGEID');
INSERT INTO Keyword (Keyword) VALUES ('CROSS');
INSERT INTO Keyword (Keyword) VALUES ('CURRENCY');
INSERT INTO Keyword (Keyword) VALUES ('CURRENT');
INSERT INTO Keyword (Keyword) VALUES ('CURRENT_DATE');
INSERT INTO Keyword (Keyword) VALUES ('CURRENT_TIME');
INSERT INTO Keyword (Keyword) VALUES ('CURRENT_TIMESTAMP');
INSERT INTO Keyword (Keyword) VALUES ('CURRENT_USER');
INSERT INTO Keyword (Keyword) VALUES ('CURSOR');
INSERT INTO Keyword (Keyword) VALUES ('CYCLE');
INSERT INTO Keyword (Keyword) VALUES ('DATE');
INSERT INTO Keyword (Keyword) VALUES ('DATE_AND_TIME');
INSERT INTO Keyword (Keyword) VALUES ('DATE_DIFF');
INSERT INTO Keyword (Keyword) VALUES ('DATEDIFF');
INSERT INTO Keyword (Keyword) VALUES ('DATENOW');
INSERT INTO Keyword (Keyword) VALUES ('DATEOF');
INSERT INTO Keyword (Keyword) VALUES ('DATEPART');
INSERT INTO Keyword (Keyword) VALUES ('DATETIME');
INSERT INTO Keyword (Keyword) VALUES ('DAY');
INSERT INTO Keyword (Keyword) VALUES ('DAYS');
INSERT INTO Keyword (Keyword) VALUES ('DEALLOCATE');
INSERT INTO Keyword (Keyword) VALUES ('DEC');
INSERT INTO Keyword (Keyword) VALUES ('DECIMAL');
INSERT INTO Keyword (Keyword) VALUES ('DECLARE');
INSERT INTO Keyword (Keyword) VALUES ('DEFAULT');
INSERT INTO Keyword (Keyword) VALUES ('DEFERRABLE');
INSERT INTO Keyword (Keyword) VALUES ('DEFERRED');
INSERT INTO Keyword (Keyword) VALUES ('DELETE');
INSERT INTO Keyword (Keyword) VALUES ('DESC');
INSERT INTO Keyword (Keyword) VALUES ('DESCRIBE');
INSERT INTO Keyword (Keyword) VALUES ('DESCRIPTOR');
INSERT INTO Keyword (Keyword) VALUES ('DIAGNOSTICS');
INSERT INTO Keyword (Keyword) VALUES ('DISCONNECT');
INSERT INTO Keyword (Keyword) VALUES ('DISTINCT');
INSERT INTO Keyword (Keyword) VALUES ('DOMAIN');
INSERT INTO Keyword (Keyword) VALUES ('DOUBLE');
INSERT INTO Keyword (Keyword) VALUES ('DROP');
INSERT INTO Keyword (Keyword) VALUES ('DURING');
INSERT INTO Keyword (Keyword) VALUES ('DYNAMIC');
INSERT INTO Keyword (Keyword) VALUES ('ELSE');
INSERT INTO Keyword (Keyword) VALUES ('END');
INSERT INTO Keyword (Keyword) VALUES ('END-EXEC');
INSERT INTO Keyword (Keyword) VALUES ('ESCAPE');
INSERT INTO Keyword (Keyword) VALUES ('EVERY');
INSERT INTO Keyword (Keyword) VALUES ('EXCEPT');
INSERT INTO Keyword (Keyword) VALUES ('EXCEPTION');
INSERT INTO Keyword (Keyword) VALUES ('EXCLUSIVE');
INSERT INTO Keyword (Keyword) VALUES ('EXEC');
INSERT INTO Keyword (Keyword) VALUES ('EXECUTE');
INSERT INTO Keyword (Keyword) VALUES ('EXISTS');
INSERT INTO Keyword (Keyword) VALUES ('EXTERNAL');
INSERT INTO Keyword (Keyword) VALUES ('EXTRACT');
INSERT INTO Keyword (Keyword) VALUES ('FALSE');
INSERT INTO Keyword (Keyword) VALUES ('FETCH');
INSERT INTO Keyword (Keyword) VALUES ('FILE');
INSERT INTO Keyword (Keyword) VALUES ('FIRST');
INSERT INTO Keyword (Keyword) VALUES ('FLOAT');
INSERT INTO Keyword (Keyword) VALUES ('FOR');
INSERT INTO Keyword (Keyword) VALUES ('FOREIGN');
INSERT INTO Keyword (Keyword) VALUES ('FORM');
INSERT INTO Keyword (Keyword) VALUES ('FORMAT_DATE');
INSERT INTO Keyword (Keyword) VALUES ('FORTRAN');
INSERT INTO Keyword (Keyword) VALUES ('FOUND');
INSERT INTO Keyword (Keyword) VALUES ('FROM');
INSERT INTO Keyword (Keyword) VALUES ('FULL');
INSERT INTO Keyword (Keyword) VALUES ('GET');
INSERT INTO Keyword (Keyword) VALUES ('GLOBAL');
INSERT INTO Keyword (Keyword) VALUES ('GO');
INSERT INTO Keyword (Keyword) VALUES ('GOTO');
INSERT INTO Keyword (Keyword) VALUES ('GRANT');
INSERT INTO Keyword (Keyword) VALUES ('GROUP');
INSERT INTO Keyword (Keyword) VALUES ('HAVING');
INSERT INTO Keyword (Keyword) VALUES ('HOUR');
INSERT INTO Keyword (Keyword) VALUES ('HOURS');
INSERT INTO Keyword (Keyword) VALUES ('HYPERLINK');
INSERT INTO Keyword (Keyword) VALUES ('IDENTIFIED');
INSERT INTO Keyword (Keyword) VALUES ('IDENTITY');
INSERT INTO Keyword (Keyword) VALUES ('IF');
INSERT INTO Keyword (Keyword) VALUES ('IMMEDIATE');
INSERT INTO Keyword (Keyword) VALUES ('IN');
INSERT INTO Keyword (Keyword) VALUES ('INCLUDE');
INSERT INTO Keyword (Keyword) VALUES ('INCLUDES');
INSERT INTO Keyword (Keyword) VALUES ('INCREMENT');
INSERT INTO Keyword (Keyword) VALUES ('INDEX');
INSERT INTO Keyword (Keyword) VALUES ('INDICATOR');
INSERT INTO Keyword (Keyword) VALUES ('INITIAL');
INSERT INTO Keyword (Keyword) VALUES ('INITIALIZATION');
INSERT INTO Keyword (Keyword) VALUES ('INITIALLY');
INSERT INTO Keyword (Keyword) VALUES ('INNER');
INSERT INTO Keyword (Keyword) VALUES ('INPUT');
INSERT INTO Keyword (Keyword) VALUES ('INSENSITIVE');
INSERT INTO Keyword (Keyword) VALUES ('INSERT');
INSERT INTO Keyword (Keyword) VALUES ('INT');
INSERT INTO Keyword (Keyword) VALUES ('INTEGER');
INSERT INTO Keyword (Keyword) VALUES ('INTERSECT');
INSERT INTO Keyword (Keyword) VALUES ('INTERVAL');
INSERT INTO Keyword (Keyword) VALUES ('INTO');
INSERT INTO Keyword (Keyword) VALUES ('IS');
INSERT INTO Keyword (Keyword) VALUES ('ISAFTER');
INSERT INTO Keyword (Keyword) VALUES ('ISBEFORE');
INSERT INTO Keyword (Keyword) VALUES ('ISDURING');
INSERT INTO Keyword (Keyword) VALUES ('ISKNOWN');
INSERT INTO Keyword (Keyword) VALUES ('IS_KNOWN');
INSERT INTO Keyword (Keyword) VALUES ('ISOLATION');
INSERT INTO Keyword (Keyword) VALUES ('JOIN');
INSERT INTO Keyword (Keyword) VALUES ('KEY');
INSERT INTO Keyword (Keyword) VALUES ('LANGUAGE');
INSERT INTO Keyword (Keyword) VALUES ('LAST');
INSERT INTO Keyword (Keyword) VALUES ('LEADING');
INSERT INTO Keyword (Keyword) VALUES ('LEFT');
INSERT INTO Keyword (Keyword) VALUES ('LEN');
INSERT INTO Keyword (Keyword) VALUES ('LEVEL');
INSERT INTO Keyword (Keyword) VALUES ('LIKE');
INSERT INTO Keyword (Keyword) VALUES ('LOCAL');
INSERT INTO Keyword (Keyword) VALUES ('LOCK');
INSERT INTO Keyword (Keyword) VALUES ('LONG');
INSERT INTO Keyword (Keyword) VALUES ('LOWER');
INSERT INTO Keyword (Keyword) VALUES ('MATCH');
INSERT INTO Keyword (Keyword) VALUES ('MAX');
INSERT INTO Keyword (Keyword) VALUES ('MAXEXTENTS');
INSERT INTO Keyword (Keyword) VALUES ('MEMO');
INSERT INTO Keyword (Keyword) VALUES ('META_PREDICATE');
INSERT INTO Keyword (Keyword) VALUES ('MIN');
INSERT INTO Keyword (Keyword) VALUES ('MINUS');
INSERT INTO Keyword (Keyword) VALUES ('MINUTE');
INSERT INTO Keyword (Keyword) VALUES ('MINUTES');
INSERT INTO Keyword (Keyword) VALUES ('MOD');
INSERT INTO Keyword (Keyword) VALUES ('MODE');
INSERT INTO Keyword (Keyword) VALUES ('MODIFY');
INSERT INTO Keyword (Keyword) VALUES ('MODULE');
INSERT INTO Keyword (Keyword) VALUES ('MONTH');
INSERT INTO Keyword (Keyword) VALUES ('MONTHS');
INSERT INTO Keyword (Keyword) VALUES ('MULTIFILE');
INSERT INTO Keyword (Keyword) VALUES ('NAME');
INSERT INTO Keyword (Keyword) VALUES ('NAMES');
INSERT INTO Keyword (Keyword) VALUES ('NATIONAL');
INSERT INTO Keyword (Keyword) VALUES ('NATURAL');
INSERT INTO Keyword (Keyword) VALUES ('NCHAR');
INSERT INTO Keyword (Keyword) VALUES ('NETSUPPORT');
INSERT INTO Keyword (Keyword) VALUES ('NEXT');
INSERT INTO Keyword (Keyword) VALUES ('NO');
INSERT INTO Keyword (Keyword) VALUES ('NOAUDIT');
INSERT INTO Keyword (Keyword) VALUES ('NOCOMPRESS');
INSERT INTO Keyword (Keyword) VALUES ('NONE');
INSERT INTO Keyword (Keyword) VALUES ('NOSPY');
INSERT INTO Keyword (Keyword) VALUES ('NOT');
INSERT INTO Keyword (Keyword) VALUES ('NOT_ONEOF');
INSERT INTO Keyword (Keyword) VALUES ('NOW');
INSERT INTO Keyword (Keyword) VALUES ('NOWAIT');
INSERT INTO Keyword (Keyword) VALUES ('NULL');
INSERT INTO Keyword (Keyword) VALUES ('NULLIF');
INSERT INTO Keyword (Keyword) VALUES ('NUMBER');
INSERT INTO Keyword (Keyword) VALUES ('NUMERIC');
INSERT INTO Keyword (Keyword) VALUES ('OCTET_LENGTH');
INSERT INTO Keyword (Keyword) VALUES ('OF');
INSERT INTO Keyword (Keyword) VALUES ('OFFLINE');
INSERT INTO Keyword (Keyword) VALUES ('ON');
INSERT INTO Keyword (Keyword) VALUES ('ONE');
INSERT INTO Keyword (Keyword) VALUES ('ONEOF');
INSERT INTO Keyword (Keyword) VALUES ('ONLINE');
INSERT INTO Keyword (Keyword) VALUES ('ONLY');
INSERT INTO Keyword (Keyword) VALUES ('OPEN');
INSERT INTO Keyword (Keyword) VALUES ('OPTION');
INSERT INTO Keyword (Keyword) VALUES ('OR');
INSERT INTO Keyword (Keyword) VALUES ('ORDER');
INSERT INTO Keyword (Keyword) VALUES ('OUTER');
INSERT INTO Keyword (Keyword) VALUES ('OUTPUT');
INSERT INTO Keyword (Keyword) VALUES ('OVERLAPS');
INSERT INTO Keyword (Keyword) VALUES ('PAD');
INSERT INTO Keyword (Keyword) VALUES ('PARTIAL');
INSERT INTO Keyword (Keyword) VALUES ('PASCAL');
INSERT INTO Keyword (Keyword) VALUES ('PASSWORD');
INSERT INTO Keyword (Keyword) VALUES ('PCTFREE');
INSERT INTO Keyword (Keyword) VALUES ('PERSONID');
INSERT INTO Keyword (Keyword) VALUES ('POSITION');
INSERT INTO Keyword (Keyword) VALUES ('PRECISION');
INSERT INTO Keyword (Keyword) VALUES ('PREPARE');
INSERT INTO Keyword (Keyword) VALUES ('PRESERVE');
INSERT INTO Keyword (Keyword) VALUES ('PRIMARY');
INSERT INTO Keyword (Keyword) VALUES ('PRIOR');
INSERT INTO Keyword (Keyword) VALUES ('PRIVILEGES');
INSERT INTO Keyword (Keyword) VALUES ('PROCEDURE');
INSERT INTO Keyword (Keyword) VALUES ('PUBLIC');
INSERT INTO Keyword (Keyword) VALUES ('Question');
INSERT INTO Keyword (Keyword) VALUES ('RANDOMISATION');
INSERT INTO Keyword (Keyword) VALUES ('RAW');
INSERT INTO Keyword (Keyword) VALUES ('READ');
INSERT INTO Keyword (Keyword) VALUES ('REAL');
INSERT INTO Keyword (Keyword) VALUES ('REFERENCES');
INSERT INTO Keyword (Keyword) VALUES ('REGISTRATION');
INSERT INTO Keyword (Keyword) VALUES ('RELATIVE');
INSERT INTO Keyword (Keyword) VALUES ('RENAME');
INSERT INTO Keyword (Keyword) VALUES ('RESOURCE');
INSERT INTO Keyword (Keyword) VALUES ('RESTRICT');
INSERT INTO Keyword (Keyword) VALUES ('RESULT_OF');
INSERT INTO Keyword (Keyword) VALUES ('REVOKE');
INSERT INTO Keyword (Keyword) VALUES ('RIGHT');
INSERT INTO Keyword (Keyword) VALUES ('ROLLBACK');
INSERT INTO Keyword (Keyword) VALUES ('ROW');
INSERT INTO Keyword (Keyword) VALUES ('ROWID');
INSERT INTO Keyword (Keyword) VALUES ('ROWLABEL');
INSERT INTO Keyword (Keyword) VALUES ('ROWNUM');
INSERT INTO Keyword (Keyword) VALUES ('ROWS');
INSERT INTO Keyword (Keyword) VALUES ('SCHEMA');
INSERT INTO Keyword (Keyword) VALUES ('SCROLL');
INSERT INTO Keyword (Keyword) VALUES ('SECOND');
INSERT INTO Keyword (Keyword) VALUES ('SECONDS');
INSERT INTO Keyword (Keyword) VALUES ('SECTION');
INSERT INTO Keyword (Keyword) VALUES ('SELECT');
INSERT INTO Keyword (Keyword) VALUES ('SESSION');
INSERT INTO Keyword (Keyword) VALUES ('SESSION_USER');
INSERT INTO Keyword (Keyword) VALUES ('SET');
INSERT INTO Keyword (Keyword) VALUES ('SHARE');
INSERT INTO Keyword (Keyword) VALUES ('SITE');
INSERT INTO Keyword (Keyword) VALUES ('SIZE');
INSERT INTO Keyword (Keyword) VALUES ('SMALLINT');
INSERT INTO Keyword (Keyword) VALUES ('SOME');
INSERT INTO Keyword (Keyword) VALUES ('SPACE');
INSERT INTO Keyword (Keyword) VALUES ('SPY');
INSERT INTO Keyword (Keyword) VALUES ('SQL');
INSERT INTO Keyword (Keyword) VALUES ('SQLCA');
INSERT INTO Keyword (Keyword) VALUES ('SQLCODE');
INSERT INTO Keyword (Keyword) VALUES ('SQLERROR');
INSERT INTO Keyword (Keyword) VALUES ('SQLSTATE');
INSERT INTO Keyword (Keyword) VALUES ('SQLWARNING');
INSERT INTO Keyword (Keyword) VALUES ('SQRT');
INSERT INTO Keyword (Keyword) VALUES ('START');
INSERT INTO Keyword (Keyword) VALUES ('STATUS');
INSERT INTO Keyword (Keyword) VALUES ('SUBSTRING');
INSERT INTO Keyword (Keyword) VALUES ('SUCCESSFUL');
INSERT INTO Keyword (Keyword) VALUES ('SUM');
INSERT INTO Keyword (Keyword) VALUES ('SYNONYM');
INSERT INTO Keyword (Keyword) VALUES ('SYSDATE');
INSERT INTO Keyword (Keyword) VALUES ('SYSTEM_USER');
INSERT INTO Keyword (Keyword) VALUES ('TABLE');
INSERT INTO Keyword (Keyword) VALUES ('TEMP');
INSERT INTO Keyword (Keyword) VALUES ('TEMPORARY');
INSERT INTO Keyword (Keyword) VALUES ('TEXT');
INSERT INTO Keyword (Keyword) VALUES ('THEN');
INSERT INTO Keyword (Keyword) VALUES ('TIME');
INSERT INTO Keyword (Keyword) VALUES ('TIME_DIFF');
INSERT INTO Keyword (Keyword) VALUES ('TIMENOW');
INSERT INTO Keyword (Keyword) VALUES ('TIMESTAMP');
INSERT INTO Keyword (Keyword) VALUES ('TIMEZONE_HOUR');
INSERT INTO Keyword (Keyword) VALUES ('TIMEZONE_MINUTE');
INSERT INTO Keyword (Keyword) VALUES ('TINYINT');
INSERT INTO Keyword (Keyword) VALUES ('TO');
INSERT INTO Keyword (Keyword) VALUES ('TRAILING');
INSERT INTO Keyword (Keyword) VALUES ('TRANSACTION');
INSERT INTO Keyword (Keyword) VALUES ('TRANSLATE');
INSERT INTO Keyword (Keyword) VALUES ('TRANSLATION');
INSERT INTO Keyword (Keyword) VALUES ('TRIGGER');
INSERT INTO Keyword (Keyword) VALUES ('TRIM');
INSERT INTO Keyword (Keyword) VALUES ('TRUE');
INSERT INTO Keyword (Keyword) VALUES ('UID');
INSERT INTO Keyword (Keyword) VALUES ('UNION');
INSERT INTO Keyword (Keyword) VALUES ('UNIQUE');
INSERT INTO Keyword (Keyword) VALUES ('UNKNOWN');
INSERT INTO Keyword (Keyword) VALUES ('UPDATE');
INSERT INTO Keyword (Keyword) VALUES ('UPPER');
INSERT INTO Keyword (Keyword) VALUES ('USAGE');
INSERT INTO Keyword (Keyword) VALUES ('USER');
INSERT INTO Keyword (Keyword) VALUES ('USING');
INSERT INTO Keyword (Keyword) VALUES ('VALIDATE');
INSERT INTO Keyword (Keyword) VALUES ('VALUE');
INSERT INTO Keyword (Keyword) VALUES ('VALUES');
INSERT INTO Keyword (Keyword) VALUES ('VARCHAR');
INSERT INTO Keyword (Keyword) VALUES ('VARCHAR2');
INSERT INTO Keyword (Keyword) VALUES ('VARYING');
INSERT INTO Keyword (Keyword) VALUES ('VIEW');
INSERT INTO Keyword (Keyword) VALUES ('VISIT');
INSERT INTO Keyword (Keyword) VALUES ('VISITCYCLENUMBER');
INSERT INTO Keyword (Keyword) VALUES ('VISITID');
INSERT INTO Keyword (Keyword) VALUES ('VOLATILE');
INSERT INTO Keyword (Keyword) VALUES ('WEEK');
INSERT INTO Keyword (Keyword) VALUES ('WEEKS');
INSERT INTO Keyword (Keyword) VALUES ('WHEN');
INSERT INTO Keyword (Keyword) VALUES ('WHENEVER');
INSERT INTO Keyword (Keyword) VALUES ('WHERE');
INSERT INTO Keyword (Keyword) VALUES ('WITH');
INSERT INTO Keyword (Keyword) VALUES ('WORK');
INSERT INTO Keyword (Keyword) VALUES ('WRITE');
INSERT INTO Keyword (Keyword) VALUES ('YEAR');
INSERT INTO Keyword (Keyword) VALUES ('YEARS');
INSERT INTO Keyword (Keyword) VALUES ('YES');
INSERT INTO Keyword (Keyword) VALUES ('YESNO');
INSERT INTO Keyword (Keyword) VALUES ('ZONE');

INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('ArezzoToken','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('AutoImportControl','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('ClinicalTest','620',1,0,1);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('ClinicalTestGroup','610',1,0,1);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('ClinicalTrial','001',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('CRFElement','140',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('CRFPage','130',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('CRFPageInstance','070',0,1,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('CTC','640',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('CTCScheme','630',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('DataItem','120',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('DataItemResponse','080',0,1,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('DataItemResponseHistory','090',0,1,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('DataItemValidation','125',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('DataType','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('EFormQGroup','210',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('Eligibility','250',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('Keyword','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('Laboratory','001',0,0,1);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('LogDetails','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('MACROControl','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('MACROCountry','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('MACRODBSetting','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('MACROLock','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('MACROTable','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('Message','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('MIMessage','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('NewDBColumn','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('NormalRange','030',0,0,1);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('Protocols','300',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('QGroup','230',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('QGroupQuestion','220',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('ReasonForChange','060',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('RequiredData','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('RSSubjectIdentifier','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('RSNextNumber','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('RSUniquenessCheck','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('Site','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('SiteLaboratory','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('StandardDataFormat','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('StudyDefinition','030',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('StudyDocument','040',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('StudyReport','190',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('StudyReportData','200',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('StudyVersion','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('StudyVisit','150',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('StudyVisitCRFPage','160',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('SubjectNumbering','270',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('TrialOffice','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('TrialPhase','510',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('TrialSite','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('TrialStatus','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('TrialStatusHistory','050',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('TrialSubject','040',0,1,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('TrialType','520',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('UniquenessCheck','260',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('UnitClasses','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('UnitConversionFactors','560',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('Units','550',1,0,1);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('UserRole','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('ValidationAction','530',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('ValidationType','540',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('ValueData','090',1,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('VisitInstance','060',0,1,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('MACROUSERSETTINGS','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('DATAIMPORT','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('LFMESSAGE','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('BATCHRESPONSEDATA','',0,0,0);

INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'CRFElement','ClinicalTestDate',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'DataItem','ClinicalTestDate',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'StudyDefinition','CTCSchemeCode',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'StudyDefinition','DOBExpr',2,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'StudyDefinition','GenderExpr',3,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'Trialsubject','SubjectGender',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'CRFPageInstance','LaboratoryCode',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'DataItemResponse','LabResult',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'DataItemResponse','CTCGrade',2,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'DataItemResponse','ClinicalTestDate',3,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'DataItemResponseHistory','LabResult',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'DataItemResponseHistory','CTCGrade',2,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,4,'DataItemResponseHistory','ClinicalTestDate',3,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,13,'TrialSubject','RegistrationStatus',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,13,'MIMessage','MIMessageResponseTimeStamp',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,13,'DataItemResponse','LaboratoryCode',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,13,'DataItemResponseHistory','LaboratoryCode',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,13,'StudyDefinition','RRServerType',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,13,'StudyDefinition','RRHTTPAddress',2,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,13,'StudyDefinition','RRUserName',3,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,13,'StudyDefinition','RRPassword',4,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,1,13,'StudyDefinition','RRProxyServer',5,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'CRFPage','eFormDatePrompt',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'NewDBColumn','ChangeType',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'NewDBColumn','ColumnNumber',2,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'CRFElement','DefaultValue',null,'#NULL#','DROPCOLUMN',28);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'CRFPageInstance','SDVStatus',1,'#NULL#','DROPCOLUMN',15);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'CRFPageInstance','ReviewStatus',2,'#NULL#','DROPCOLUMN',14);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'DataItem','ExternalDataSource',1,'#NULL#','DROPCOLUMN',19);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'DataItem','RequiredTrialTypeId',2,'#NULL#','DROPCOLUMN',16);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'DataItem','Required',3,'#NULL#','DROPCOLUMN',15);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'DataItemResponse','SDVStatus',1,'#NULL#','DROPCOLUMN',25);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'DataItemResponse','ReviewStatus',2,'#NULL#','DROPCOLUMN',24);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'DataItemResponse','ReviewComment',3,'#NULL#','DROPCOLUMN',18);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'DataItemResponseHistory','SDVStatus',1,'#NULL#','DROPCOLUMN',25);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'DataItemResponseHistory','ReviewStatus',2,'#NULL#','DROPCOLUMN',24);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'DataItemResponseHistory','ReviewComment',3,'#NULL#','DROPCOLUMN',18);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'MACROControl','DateReference',null,'#NULL#','DROPCOLUMN',2);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'StudyReport','HideBlankRows',null,'#NULL#','DROPCOLUMN',4);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'StudyReportData','HideBlankRows',null,'#NULL#','DROPCOLUMN',4);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'TrialOffice','TransferSchedule',null,'#NULL#','DROPCOLUMN',7);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'TrialSubject','SDVStatus',1,'#NULL#','DROPCOLUMN',18);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'TrialSubject','ReviewStatus',2,'#NULL#','DROPCOLUMN',17);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'TrialSubject','Checksum',3,'#NULL#','DROPCOLUMN',15);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'TrialSubject','Initials',4,'#NULL#','DROPCOLUMN',7);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'TrialSubject','Surname',5,'#NULL#','DROPCOLUMN',6);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'TrialSubject','Forename',6,'#NULL#','DROPCOLUMN',5);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'TrialSubject','SubjectIdentificationCode',7,'#NULL#','DROPCOLUMN',4);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'UnitConversionFactors','ConversionExpression',null,'#NULL#','DROPCOLUMN',5);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'ValueData','DefaultCat',null,'#NULL#','DROPCOLUMN',9);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'VisitInstance','SDVStatus',1,'#NULL#','DROPCOLUMN',12);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,1,'VisitInstance','ReviewStatus',2,'#NULL#','DROPCOLUMN',11);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,10,'DataItemResponse','HadValue',null,'1','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,10,'DataItemResponseHistory','HadValue',null,'1','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,10,'ClinicalTrial','ActualRecruitment',null,'#NULL#','DROPCOLUMN',8);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (2,2,10,'TrialSite','TrialSiteActualRecruitment',null,'#NULL#','DROPCOLUMN',3);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,3,'CRFElement','OwnerQGroupID',1,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,3,'CRFElement','QGroupID',2,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,3,'CRFElement','QGroupFieldOrder',3,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,3,'CRFElement','ShowStatusFlag',4,'1','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,3,'DataItemResponse','RepeatNumber',null,'1','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,3,'DataItemResponseHistory','RepeatNumber',null,'1','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,3,'MIMessage','MIMessageResponseCycle',null,'1','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,4,'CRFElement','CaptionFontName',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,4,'CRFElement','CaptionFontBold',2,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,4,'CRFElement','CaptionFontItalic',3,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,4,'CRFElement','CaptionFontSize',4,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,4,'CRFElement','CaptionFontColour',5,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'DataItemResponse','ChangeCount',1,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'DataItemResponse','DiscrepancyStatus',2,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'DataItemResponse','SDVStatus',3,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'DataItemResponse','NoteStatus',4,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'CRFPageInstance','DiscrepancyStatus',1,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'CRFPageInstance','SDVStatus',2,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'CRFPageInstance','NoteStatus',3,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'VisitInstance','DiscrepancyStatus',1,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'VisitInstance','SDVStatus',2,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'VisitInstance','NoteStatus',3,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'TrialSubject','DiscrepancyStatus',1,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'TrialSubject','SDVStatus',2,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,5,'TrialSubject','NoteStatus',3,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,7,'DataItem','MACROOnly',1,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,7,'DataItem','Description',2,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,7,'StudyDefinition','AREZZOUpdateStatus',1,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,8,'Message','MessageReceivedTimeStamp',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,8,'Site','SiteLocation',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,8,'TrialSite','StudyVersion',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,8,'CRFElement','ElementUse',1,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,8,'StudyVisitCRFPage','eFormUse',1,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,10,'CRFElement','DisplayLength',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,10,'StudyVisit','Repeating',1,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'TrialSubject','ImportTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'VisitInstance','ImportTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'CRFPageInstance','ImportTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'QGroupInstance','ImportTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'DataItemResponse','ResponseTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'DataItemResponse','ImportTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'DataItemResponse','DatabaseTimestamp',null,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'DataItemResponse','DatabaseTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'DataItemResponseHistory','ResponseTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'DataItemResponseHistory','ImportTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'DataItemResponseHistory','DatabaseTimestamp',null,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'DataItemResponseHistory','DatabaseTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'MIMessage','MIMessageCreated_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'MIMessage','MIMessageSent_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'MIMessage','MIMessageReceived_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'Message','MessageTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'Message','MessageReceivedTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'RSUniquenessCheck','CheckTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'StudyVersion','VersionTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,13,'TrialStatusHistory','StatusChangedTimestamp_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,14,'ReasonForChange','ReasonType',null,'0','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,18,'Site','SiteCountry',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,18,'LogDetails','LogDateTime_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,18,'LogDetails','Location',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,19,'CRFPAGE','EFORMWIDTH',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,20,'CRFELEMENT','HOTLINK',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,21,'TRIALSUBJECT','SEQUENCEID',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,21,'VISITINSTANCE','SEQUENCEID',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,21,'CRFPAGEINSTANCE','SEQUENCEID',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,21,'DATAITEMRESPONSE','SEQUENCEID',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,21,'DATAITEMRESPONSEHISTORY','SEQUENCEID',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,21,'MIMESSAGE','SEQUENCEID',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,23,'MIMESSAGE','MIMESSAGECRFPAGEID',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,23,'MIMESSAGE','MIMESSAGECRFPAGECYCLE',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,23,'MIMESSAGE','MIMESSAGEDATAITEMID',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,24,'LOGDETAILS','STATUS',1,'0','NEWCOLUMN',NULL);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,25,'STUDYDEFINITION','AREZZOMEMORY',1,'0','NEWCOLUMN',NULL);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,31,'DATAITEMRESPONSE','STANDARDVALUE',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,31,'DATAITEMRESPONSEHISTORY','STANDARDVALUE',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,32,'DATAITEMRESPONSE','USERNAMEFULL',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,32,'DATAITEMRESPONSEHISTORY','USERNAMEFULL',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,38,'TRIALSUBJECT','SUBJECTTIMESTAMP',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,38,'TRIALSUBJECT','SUBJECTTIMESTAMP_TZ',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,46,'CRFELEMENT','DESCRIPTION',null,'#NULL#','NEWCOLUMN',null);

INSERT INTO Protocols (FileName,ProtocolName,Version,Description,Author,Created,Modified,ArezzoVersion,InUse,ArezzoFile) VALUES ('Library','Library','1','This Protocol is the library','InferMed Ltd',36523.0 ,36523.0 ,'2.1',0,'''CLM FILE''(1998,4). clma_guideline(10000). clma_task(10000,`library`,plan,`Library`). clma_task_attr(10000,caption,''Library'',`Library`). clma_locked(10000). clma_key(10001). ');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (1,0,'AA99AA');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (2,0,'AAAAA');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (4,2,'9999');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (5,2,'99');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (6,3,'99.99');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (7,3,'99.999');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (8,3,'9.999');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (9,3,'.999');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (10,4,'dd/mm/yyyy');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (11,4,'mm/dd/yyyy');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (12,4,'hh:mm');
INSERT INTO StandardDataFormat (StandardDataFormatId,DataTypeId,DataFormat) VALUES (13,4,'hh:mm:ss');

INSERT INTO StudyDefinition (ClinicalTrialId,VersionId,DefaultFontColour,DefaultCRFPageColour,DefaultFontName,DefaultFontBold,DefaultFontItalic,DefaultFontSize,UserName,StudyDefinitionTimestamp,TrialSubjectLabel,LocalTrialSubjectLabel,StandardDateFormat,StandardTimeFormat,SingleUseDataItems) VALUES (0,0,-2147483630,12632256,'Arial',0,0,10,'InferMed',36525.0,'',0,'','',0);

INSERT INTO TrialPhase (PhaseId,PhaseName) VALUES (1,'I');
INSERT INTO TrialPhase (PhaseId,PhaseName) VALUES (2,'II');
INSERT INTO TrialPhase (PhaseId,PhaseName) VALUES (3,'III');
INSERT INTO TrialPhase (PhaseId,PhaseName) VALUES (4,'IV');
INSERT INTO TrialStatus (StatusId,StatusName) VALUES (1,'In preparation');
INSERT INTO TrialStatus (StatusId,StatusName) VALUES (2,'Open');
INSERT INTO TrialStatus (StatusId,StatusName) VALUES (3,'Closed to recruitment');
INSERT INTO TrialStatus (StatusId,StatusName) VALUES (4,'Closed to follow up');
INSERT INTO TrialStatus (StatusId,StatusName) VALUES (5,'Suspended');
INSERT INTO TrialStatus (StatusId,StatusName) VALUES (6,'Deleted');

INSERT INTO UnitClasses (UnitClass) VALUES ('Individual');
INSERT INTO UnitClasses (UnitClass) VALUES ('Length');
INSERT INTO UnitClasses (UnitClass) VALUES ('Temperature');
INSERT INTO UnitClasses (UnitClass) VALUES ('Volume');
INSERT INTO UnitClasses (UnitClass) VALUES ('Weight');

INSERT INTO UnitConversionFactors (FromUnit,ToUnit,ConversionFactor,UnitClass) VALUES ('cm','m',0.01,'Length');
INSERT INTO UnitConversionFactors (FromUnit,ToUnit,ConversionFactor,UnitClass) VALUES ('cm','mm',10,'Length');
INSERT INTO UnitConversionFactors (FromUnit,ToUnit,ConversionFactor,UnitClass) VALUES ('g','kg',0.001,'Weight');
INSERT INTO UnitConversionFactors (FromUnit,ToUnit,ConversionFactor,UnitClass) VALUES ('kg','g',1000,'Weight');
INSERT INTO UnitConversionFactors (FromUnit,ToUnit,ConversionFactor,UnitClass) VALUES ('km','m',1000,'Length');
INSERT INTO UnitConversionFactors (FromUnit,ToUnit,ConversionFactor,UnitClass) VALUES ('m','cm',100,'Length');
INSERT INTO UnitConversionFactors (FromUnit,ToUnit,ConversionFactor,UnitClass) VALUES ('m','mm',1000,'Length');
INSERT INTO UnitConversionFactors (FromUnit,ToUnit,ConversionFactor,UnitClass) VALUES ('mm','cm',0.1,'Length');
INSERT INTO UnitConversionFactors (FromUnit,ToUnit,ConversionFactor,UnitClass) VALUES ('mm','m',0.001,'Length');

INSERT INTO Units (Unit,UnitClass) VALUES ('cm','Length');
INSERT INTO Units (Unit,UnitClass) VALUES ('g','Weight');
INSERT INTO Units (Unit,UnitClass) VALUES ('kg','Weight');
INSERT INTO Units (Unit,UnitClass) VALUES ('km','Length');
INSERT INTO Units (Unit,UnitClass) VALUES ('m','Length');
INSERT INTO Units (Unit,UnitClass) VALUES ('mm','Length');

INSERT INTO ValidationAction (ValidationActionId,ValidationActionName) VALUES (0,'Reject data if');
INSERT INTO ValidationAction (ValidationActionId,ValidationActionName) VALUES (1,'Warn if');
INSERT INTO ValidationAction (ValidationActionId,ValidationActionName) VALUES (2,'Flag if');
INSERT INTO ValidationType (ValidationTypeId,ValidationTypeName,ValidationActionId) VALUES (0,'Reject data if',0);
INSERT INTO ValidationType (ValidationTypeId,ValidationTypeName,ValidationActionId) VALUES (1,'Warn if',1);
INSERT INTO ValidationType (ValidationTypeId,ValidationTypeName,ValidationActionId) VALUES (2,'Flag if',2);

INSERT INTO MACROCountry VALUES (1001,'AFGHANISTAN'); 
INSERT INTO MACROCountry VALUES (1002,'ALBANIA'); 
INSERT INTO MACROCountry VALUES (1003,'ALGERIA'); 
INSERT INTO MACROCountry VALUES (1004,'AMERICAN SAMOA');
INSERT INTO MACROCountry VALUES (1005,'ANDORRA'); 
INSERT INTO MACROCountry VALUES (1006,'ANGOLA'); 
INSERT INTO MACROCountry VALUES (1007,'ANGUILLA'); 
INSERT INTO MACROCountry VALUES (1008,'ANTARCTICA'); 
INSERT INTO MACROCountry VALUES (1009,'ANTIGUA AND BARBUDA'); 
INSERT INTO MACROCountry VALUES (1010,'ARGENTINA'); 
INSERT INTO MACROCountry VALUES (1011,'ARMENIA'); 
INSERT INTO MACROCountry VALUES (1012,'ARUBA'); 
INSERT INTO MACROCountry VALUES (1013,'AUSTRALIA'); 
INSERT INTO MACROCountry VALUES (1014,'AUSTRIA'); 
INSERT INTO MACROCountry VALUES (1015,'AZERBAIJAN'); 
INSERT INTO MACROCountry VALUES (1016,'BAHAMAS'); 
INSERT INTO MACROCountry VALUES (1017,'BAHRAIN'); 
INSERT INTO MACROCountry VALUES (1018,'BANGLADESH'); 
INSERT INTO MACROCountry VALUES (1019,'BARBADOS'); 
INSERT INTO MACROCountry VALUES (1020,'BELARUS'); 
INSERT INTO MACROCountry VALUES (1021,'BELGIUM'); 
INSERT INTO MACROCountry VALUES (1022,'BELIZE'); 
INSERT INTO MACROCountry VALUES (1023,'BENIN'); 
INSERT INTO MACROCountry VALUES (1024,'BERMUDA'); 
INSERT INTO MACROCountry VALUES (1025,'BHUTAN'); 
INSERT INTO MACROCountry VALUES (1026,'BOLIVIA'); 
INSERT INTO MACROCountry VALUES (1027,'BOSNIA AND HERZEGOVINA'); 
INSERT INTO MACROCountry VALUES (1028,'BOUVET ISLAND'); 
INSERT INTO MACROCountry VALUES (1029,'BRAZIL');
INSERT INTO MACROCountry VALUES (1030,'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO MACROCountry VALUES (1031,'BRUNEI DARUSSALAM'); 
INSERT INTO MACROCountry VALUES (1032,'BULGARIA');   
INSERT INTO MACROCountry VALUES (1034,'BURKINA FASO'); 
INSERT INTO MACROCountry VALUES (1035,'BURUNDI'); 
INSERT INTO MACROCountry VALUES (1036,'CAMBODIA'); 
INSERT INTO MACROCountry VALUES (1037,'CAMEROON'); 
INSERT INTO MACROCountry VALUES (1038,'CANADA'); 
INSERT INTO MACROCountry VALUES (1039,'CAPE VERDE'); 
INSERT INTO MACROCountry VALUES (1040,'CAYMAN ISLANDS'); 
INSERT INTO MACROCountry VALUES (1041,'CENTRAL AFRICAN REPUBLIC'); 
INSERT INTO MACROCountry VALUES (1042,'CHAD'); 
INSERT INTO MACROCountry VALUES (1043,'CHILE'); 
INSERT INTO MACROCountry VALUES (1044,'CHINA'); 
INSERT INTO MACROCountry VALUES (1045,'CHRISTMAS ISLAND'); 
INSERT INTO MACROCountry VALUES (1046,'COCOS (KEELING) ISLANDS'); 
INSERT INTO MACROCountry VALUES (1047,'COLOMBIA'); 
INSERT INTO MACROCountry VALUES (1048,'COMOROS'); 
INSERT INTO MACROCountry VALUES (1049,'CONGO'); 
INSERT INTO MACROCountry VALUES (1050,'CONGO, THE DEMOCRATIC REPUBLIC OF THE');
INSERT INTO MACROCountry VALUES (1051,'COOK ISLANDS'); 
INSERT INTO MACROCountry VALUES (1052,'COSTA RICA');  
INSERT INTO MACROCountry VALUES (1053,'CÔTE D,IVOIRE'); 
INSERT INTO MACROCountry VALUES (1054,'CROATIA'); 
INSERT INTO MACROCountry VALUES (1055,'CUBA'); 
INSERT INTO MACROCountry VALUES (1056,'CYPRUS'); 
INSERT INTO MACROCountry VALUES (1057,'CZECH REPUBLIC'); 
INSERT INTO MACROCountry VALUES (1058,'DENMARK'); 
INSERT INTO MACROCountry VALUES (1059,'DJIBOUTI');
INSERT INTO MACROCountry VALUES (1060,'DOMINICA'); 
INSERT INTO MACROCountry VALUES (1061,'DOMINICAN REPUBLIC'); 
INSERT INTO MACROCountry VALUES (1062,'ECUADOR'); 
INSERT INTO MACROCountry VALUES (1063,'EGYPT'); 
INSERT INTO MACROCountry VALUES (1064,'EL SALVADOR');
INSERT INTO MACROCountry VALUES (1065,'EQUATORIAL GUINEA'); 
INSERT INTO MACROCountry VALUES (1066,'ERITREA'); 
INSERT INTO MACROCountry VALUES (1067,'ESTONIA');  
INSERT INTO MACROCountry VALUES (1068,'ETHIOPIA'); 
INSERT INTO MACROCountry VALUES (1069,'FALKLAND ISLANDS (MALVINAS)'); 
INSERT INTO MACROCountry VALUES (1070,'FAROE ISLANDS'); 
INSERT INTO MACROCountry VALUES (1071,'FIJI'); 
INSERT INTO MACROCountry VALUES (1072,'FINLAND'); 
INSERT INTO MACROCountry VALUES (1073,'FRANCE'); 
INSERT INTO MACROCountry VALUES (1074,'FRENCH GUIANA'); 
INSERT INTO MACROCountry VALUES (1075,'FRENCH POLYNESIA');
INSERT INTO MACROCountry VALUES (1076,'FRENCH SOUTHERN TERRITORIES'); 
INSERT INTO MACROCountry VALUES (1077,'GABON');  
INSERT INTO MACROCountry VALUES (1078,'GAMBIA'); 
INSERT INTO MACROCountry VALUES (1079,'GEORGIA'); 
INSERT INTO MACROCountry VALUES (1080,'GERMANY'); 
INSERT INTO MACROCountry VALUES (1081,'GHANA');
INSERT INTO MACROCountry VALUES (1082,'GIBRALTAR');  
INSERT INTO MACROCountry VALUES (1083,'GREECE'); 
INSERT INTO MACROCountry VALUES (1084,'GREENLAND'); 
INSERT INTO MACROCountry VALUES (1085,'GRENADA'); 
INSERT INTO MACROCountry VALUES (1086,'GUADELOUPE'); 
INSERT INTO MACROCountry VALUES (1087,'GUAM'); 
INSERT INTO MACROCountry VALUES (1088,'GUATEMALA');
INSERT INTO MACROCountry VALUES (1089,'GUINEA'); 
INSERT INTO MACROCountry VALUES (1090,'GUINEA-BISSAU');
INSERT INTO MACROCountry VALUES (1091,'GUYANA'); 
INSERT INTO MACROCountry VALUES (1092,'HAITI') 
INSERT INTO MACROCountry VALUES (1093,'HEARD ISLAND AND MCDONALD ISLANDS');
INSERT INTO MACROCountry VALUES (1094,'HOLY SEE (VATICAN CITY STATE)');
INSERT INTO MACROCountry VALUES (1095,'HONDURAS');
INSERT INTO MACROCountry VALUES (1096,'HONG KONG'); 
INSERT INTO MACROCountry VALUES (1097,'HUNGARY'); 
INSERT INTO MACROCountry VALUES (1098,'ICELAND');
INSERT INTO MACROCountry VALUES (1099,'INDIA'); 
INSERT INTO MACROCountry VALUES (1100,'INDONESIA');
INSERT INTO MACROCountry VALUES (1101,'IRAN, ISLAMIC REPUBLIC OF'); 
INSERT INTO MACROCountry VALUES (1102,'IRAQ'); 
INSERT INTO MACROCountry VALUES (1103,'IRELAND'); 
INSERT INTO MACROCountry VALUES (1104,'ISRAEL');
INSERT INTO MACROCountry VALUES (1105,'ITALY');  
INSERT INTO MACROCountry VALUES (1106,'JAMAICA'); 
INSERT INTO MACROCountry VALUES (1107,'JAPAN'); 
INSERT INTO MACROCountry VALUES (1108,'JORDAN'); 
INSERT INTO MACROCountry VALUES (1109,'KAZAKHSTAN');
INSERT INTO MACROCountry VALUES (1110,'KENYA'); 
INSERT INTO MACROCountry VALUES (1111,'KIRIBATI'); 
INSERT INTO MACROCountry VALUES (1112,'KOREA, DEMOCRATIC REPUBLIC OF');
INSERT INTO MACROCountry VALUES (1113,'KOREA, REPUBLIC OF');  
INSERT INTO MACROCountry VALUES (1114,'KUWAIT'); 
INSERT INTO MACROCountry VALUES (1115,'KYRGYZSTAN');
INSERT INTO MACROCountry VALUES (1116,'LAO,DEMOCRATIC REPUBLIC OF'); 
INSERT INTO MACROCountry VALUES (1117,'LATVIA');  
INSERT INTO MACROCountry VALUES (1118,'LEBANON'); 
INSERT INTO MACROCountry VALUES (1119,'LESOTHO'); 
INSERT INTO MACROCountry VALUES (1120,'LIBERIA');  
INSERT INTO MACROCountry VALUES (1121,'LIBYAN ARAB JAMAHIRIYA'); 
INSERT INTO MACROCountry VALUES (1122,'LIECHTENSTEIN'); 
INSERT INTO MACROCountry VALUES (1123,'LITHUANIA'); 
INSERT INTO MACROCountry VALUES (1124,'LUXEMBOURG'); 
INSERT INTO MACROCountry VALUES (1125,'MACAO'); 
INSERT INTO MACROCountry VALUES (1126,'MACEDONIA'); 
INSERT INTO MACROCountry VALUES (1127,'MADAGASCAR');
INSERT INTO MACROCountry VALUES (1128,'MALAWI'); 
INSERT INTO MACROCountry VALUES (1129,'MALAYSIA'); 
INSERT INTO MACROCountry VALUES (1130,'MALDIVES');
INSERT INTO MACROCountry VALUES (1131,'MALI') ;
INSERT INTO MACROCountry VALUES (1132,'MALTA'); 
INSERT INTO MACROCountry VALUES (1133,'MARSHALL ISLANDS');
INSERT INTO MACROCountry VALUES (1134,'MARTINIQUE');
INSERT INTO MACROCountry VALUES (1135,'MAURITANIA');
INSERT INTO MACROCountry VALUES (1136,'MAURITIUS');
INSERT INTO MACROCountry VALUES (1137,'MAYOTTE');
INSERT INTO MACROCountry VALUES (1138,'MEXICO');
INSERT INTO MACROCountry VALUES (1139,'MICRONESIA, FEDERATED STATES OF');
INSERT INTO MACROCountry VALUES (1140,'MOLDOVA, REPUBLIC OF');
INSERT INTO MACROCountry VALUES (1141,'MONACO'); 
INSERT INTO MACROCountry VALUES (1142,'MONGOLIA');  
INSERT INTO MACROCountry VALUES (1143,'MONTSERRAT'); 
INSERT INTO MACROCountry VALUES (1144,'MOROCCO');
INSERT INTO MACROCountry VALUES (1145,'MOZAMBIQUE');
INSERT INTO MACROCountry VALUES (1146,'MYANMAR');
INSERT INTO MACROCountry VALUES (1147,'NAMIBIA');
INSERT INTO MACROCountry VALUES (1148,'NAURU'); 
INSERT INTO MACROCountry VALUES (1149,'NEPAL');   
INSERT INTO MACROCountry VALUES (1150,'NETHERLANDS');
INSERT INTO MACROCountry VALUES (1151,'NETHERLANDS ANTILLES');
INSERT INTO MACROCountry VALUES (1152,'NEW CALEDONIA');
INSERT INTO MACROCountry VALUES (1153,'NEW ZEALAND');
INSERT INTO MACROCountry VALUES (1154,'NICARAGUA');
INSERT INTO MACROCountry VALUES (1155,'NIGER'); 
INSERT INTO MACROCountry VALUES (1156,'NIGERIA'); 
INSERT INTO MACROCountry VALUES (1157,'NIUE');
INSERT INTO MACROCountry VALUES (1158,'NORFOLK ISLAND'); 
INSERT INTO MACROCountry VALUES (1159,'NORTHERN MARIANA ISLANDS');
INSERT INTO MACROCountry VALUES (1160,'NORWAY'); 
INSERT INTO MACROCountry VALUES (1161,'OMAN'); 
INSERT INTO MACROCountry VALUES (1162,'PAKISTAN');
INSERT INTO MACROCountry VALUES (1163,'PALAU');
INSERT INTO MACROCountry VALUES (1164,'PALESTINIAN TERRITORY');
INSERT INTO MACROCountry VALUES (1165,'PANAMA'); 
INSERT INTO MACROCountry VALUES (1166,'PAPUA NEW GUINEA');
INSERT INTO MACROCountry VALUES (1167,'PARAGUAY'); 
INSERT INTO MACROCountry VALUES (1168,'PERU'); 
INSERT INTO MACROCountry VALUES (1169,'PHILIPPINES'); 
INSERT INTO MACROCountry VALUES (1170,'PITCAIRN'); 
INSERT INTO MACROCountry VALUES (1171,'POLAND'); 
INSERT INTO MACROCountry VALUES (1172,'PORTUGAL');
INSERT INTO MACROCountry VALUES (1173,'PUERTO RICO');
INSERT INTO MACROCountry VALUES (1174,'QATAR'); 
INSERT INTO MACROCountry VALUES (1175,'RÉUNION'); 
INSERT INTO MACROCountry VALUES (1176,'RUSSIAN FEDERATION'); 
INSERT INTO MACROCountry VALUES (1177,'RWANDA');
INSERT INTO MACROCountry VALUES (1178,'SAINT HELENA');
INSERT INTO MACROCountry VALUES (1179,'SAINT KITTS AND NEVIS'); 
INSERT INTO MACROCountry VALUES (1180,'SAINT LUCIA'); 
INSERT INTO MACROCountry VALUES (1181,'SAINT PIERRE AND MIQUELON'); 
INSERT INTO MACROCountry VALUES (1182,'SAINT VINCENT AND THE GRENADINES');
INSERT INTO MACROCountry VALUES (1183,'SAMOA'); 
INSERT INTO MACROCountry VALUES (1184,'SAN MARINO');
INSERT INTO MACROCountry VALUES (1185,'SAO TOME AND PRINCIPE'); 
INSERT INTO MACROCountry VALUES (1186,'SAUDI ARABIA'); 
INSERT INTO MACROCountry VALUES (1187,'SENEGAL'); 
INSERT INTO MACROCountry VALUES (1188,'SEYCHELLES'); 
INSERT INTO MACROCountry VALUES (1189,'SIERRA LEONE'); 
INSERT INTO MACROCountry VALUES (1190,'SINGAPORE'); 
INSERT INTO MACROCountry VALUES (1191,'SLOVAKIA');
INSERT INTO MACROCountry VALUES (1192,'SLOVENIA');  
INSERT INTO MACROCountry VALUES (1193,'SOLOMON ISLANDS'); 
INSERT INTO MACROCountry VALUES (1194,'SOMALIA'); 
INSERT INTO MACROCountry VALUES (1195,'SOUTH AFRICA'); 
INSERT INTO MACROCountry VALUES (1196,'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'); 
INSERT INTO MACROCountry VALUES (1197,'SPAIN'); 
INSERT INTO MACROCountry VALUES (1198,'SRI LANKA'); 
INSERT INTO MACROCountry VALUES (1199,'SUDAN');
INSERT INTO MACROCountry VALUES (1200,'SURINAME');
INSERT INTO MACROCountry VALUES (1201,'SVALBARD AND JAN MAYEN');  
INSERT INTO MACROCountry VALUES (1202,'SWAZILAND'); 
INSERT INTO MACROCountry VALUES (1203,'SWEDEN'); 
INSERT INTO MACROCountry VALUES (1204,'SWITZERLAND');  
INSERT INTO MACROCountry VALUES (1205,'SYRIAN ARAB REPUBLIC'); 
INSERT INTO MACROCountry VALUES (1206,'TAIWAN, PROVINCE OF CHINA');  
INSERT INTO MACROCountry VALUES (1207,'TAJIKISTAN'); 
INSERT INTO MACROCountry VALUES (1208,'TANZANIA, UNITED REPUBLIC OF');
INSERT INTO MACROCountry VALUES (1209,'THAILAND'); 
INSERT INTO MACROCountry VALUES (1210,'TIMOR-LESTE'); 
INSERT INTO MACROCountry VALUES (1211,'TOGO'); 
INSERT INTO MACROCountry VALUES (1212,'TOKELAU');
INSERT INTO MACROCountry VALUES (1213,'TONGA');
INSERT INTO MACROCountry VALUES (1214,'TRINIDAD AND TOBAGO');
INSERT INTO MACROCountry VALUES (1215,'TUNISIA'); 
INSERT INTO MACROCountry VALUES (1216,'TURKEY'); 
INSERT INTO MACROCountry VALUES (1217,'TURKMENISTAN'); 
INSERT INTO MACROCountry VALUES (1218,'TURKS AND CAICOS ISLANDS'); 
INSERT INTO MACROCountry VALUES (1219,'TUVALU');
INSERT INTO MACROCountry VALUES (1220,'UGANDA');
INSERT INTO MACROCountry VALUES (1221,'UKRAINE');
INSERT INTO MACROCountry VALUES (1222,'UNITED ARAB EMIRATES'); 
INSERT INTO MACROCountry VALUES (1223,'UNITED KINGDOM'); 
INSERT INTO MACROCountry VALUES (1224,'UNITED STATES'); 
INSERT INTO MACROCountry VALUES (1225,'UNITED STATES MINOR OUTLYING ISLANDS');
INSERT INTO MACROCountry VALUES (1226,'URUGUAY');
INSERT INTO MACROCountry VALUES (1227,'UZBEKISTAN');
INSERT INTO MACROCountry VALUES (1228,'VANUATU');
INSERT INTO MACROCountry VALUES (1229,'Vatican City State');
INSERT INTO MACROCountry VALUES (1230,'VENEZUELA'); 
INSERT INTO MACROCountry VALUES (1231,'VIET NAM'); 
INSERT INTO MACROCountry VALUES (1232,'VIRGIN ISLANDS, BRITISH');
INSERT INTO MACROCountry VALUES (1233,'VIRGIN ISLANDS, U.S.');
INSERT INTO MACROCountry VALUES (1234,'WALLIS AND FUTUNA'); 
INSERT INTO MACROCountry VALUES (1235,'WESTERN SAHARA'); 
INSERT INTO MACROCountry VALUES (1236,'YEMEN'); 
INSERT INTO MACROCountry VALUES (1237,'YUGOSLAVIA'); 
INSERT INTO MACROCountry VALUES (1238,'ZAIRE');
INSERT INTO MACROCountry VALUES (1239,'ZAMBIA');  
INSERT INTO MACROCountry VALUES (1250,'ZIMBABWE');
INSERT INTO MACROCountry VALUES (1251,'ROMANIA');   

INSERT INTO MACRODBSetting VALUES('datatransfer','dbtype','server');