CREATE TABLE DATABASES( DATABASECODE VARCHAR(15) NOT NULL,  HTMLLOCATION VARCHAR(255),  DATABASELOCATION VARCHAR(255),  DATABASETYPE SMALLINT,  SERVERNAME VARCHAR(50),  NAMEOFDATABASE VARCHAR(50),  DATABASEUSER VARCHAR(100),  DATABASEPASSWORD VARCHAR(100),  SECUREHTMLLOCATION VARCHAR(255),  REPORTSLOCATION VARCHAR(255), CONSTRAINT PKDATABASES PRIMARY KEY (DATABASECODE));

CREATE TABLE MACROFUNCTION( FUNCTIONCODE VARCHAR(15) NOT NULL,  MACROFUNCTION VARCHAR(255), CONSTRAINT PKMACROFUNCTION PRIMARY KEY (FUNCTIONCODE));

CREATE TABLE LOGINLOG( LOGDATETIME DECIMAL(16,10) NOT NULL,  LOGNUMBER INT NOT NULL,  TASKID VARCHAR(50) NOT NULL,  LOGMESSAGE VARCHAR(255),  USERNAME VARCHAR(20),  LOGDATETIME_TZ SMALLINT,  LOCATION VARCHAR(50) NOT NULL,  STATUS SMALLINT, CONSTRAINT PKLOGINLOG PRIMARY KEY (LOGDATETIME, LOGNUMBER, TASKID, LOCATION));

CREATE TABLE MACROPASSWORD( MINLENGTH SMALLINT,  MAXLENGTH SMALLINT,  EXPIRYPERIOD SMALLINT,  ENFORCEMIXEDCASE SMALLINT,  ENFORCEDIGIT SMALLINT,  ALLOWREPEATCHARS SMALLINT,  ALLOWUSERNAME SMALLINT,  PASSWORDHISTORY SMALLINT,  PASSWORDRETRIES SMALLINT);

CREATE TABLE MACROUSER( USERNAME VARCHAR(20) NOT NULL,  USERNAMEFULL VARCHAR(100),  USERPASSWORD VARCHAR(100),  ENABLED SMALLINT,  LASTLOGIN DECIMAL(16,10),  FIRSTLOGIN DECIMAL(16,10),  DEFAULTUSERROLECODE VARCHAR(15),  FAILEDATTEMPTS SMALLINT,  PASSWORDCREATED DECIMAL(16,10),  SYSADMIN SMALLINT, CONSTRAINT PKMACROUSER PRIMARY KEY (USERNAME));

CREATE TABLE ONLINESUPPORT( SUPPORTUSERNAME VARCHAR(50),  SUPPORTUSERPASSWORD VARCHAR(50),  SUPPORTURL VARCHAR(255));

CREATE TABLE PASSWORDHISTORY( USERNAME VARCHAR(20) NOT NULL,  HISTORYNUMBER SMALLINT NOT NULL,  PASSWORDCREATED DECIMAL(16,10),  USERPASSWORD VARCHAR(100), CONSTRAINT PKPASSWORDHISTORY PRIMARY KEY (USERNAME, HISTORYNUMBER));

CREATE TABLE ROLE( ROLECODE VARCHAR(15) NOT NULL,  ROLEDESCRIPTION VARCHAR(255),  ENABLED SMALLINT,  SYSADMIN SMALLINT, CONSTRAINT PKROLE PRIMARY KEY (ROLECODE));

CREATE TABLE ROLEFUNCTION( ROLECODE VARCHAR(15) NOT NULL,  FUNCTIONCODE VARCHAR(15) NOT NULL, CONSTRAINT PKROLEFUNCTION PRIMARY KEY (ROLECODE, FUNCTIONCODE));

CREATE TABLE SECURITYCONTROL( SECURITYMODE INT,  MACROVERSION VARCHAR(15),  BUILDSUBVERSION VARCHAR(5));

CREATE TABLE USERDATABASE( USERNAME VARCHAR(20) NOT NULL,  DATABASECODE VARCHAR(15) NOT NULL, CONSTRAINT PKUSERDATABASE PRIMARY KEY (USERNAME, DATABASECODE));

CREATE TABLE FUNCTIONMODULE( FUNCTIONCODE VARCHAR(15) NOT NULL,  MACROMODULE VARCHAR(15) NOT NULL);


