CREATE TABLE AREZZOTOKEN( AREZZOID VARCHAR(50) NOT NULL,  DBTOKEN INT,  CLINICALTRIALID INT,  TRIALSITE VARCHAR(8),  PERSONID INT, CONSTRAINT PKAREZZOTOKEN PRIMARY KEY (AREZZOID));

CREATE TABLE AUTOIMPORTCONTROL( UPLOADORDER SMALLINT NOT NULL,  STARTSTOP VARCHAR(10),  WAITINTERVAL INT, CONSTRAINT PKUPLOADORDER PRIMARY KEY (UPLOADORDER));

CREATE TABLE BATCHRESPONSEDATA( BATCHRESPONSEID INT NOT NULL,  CLINICALTRIALID INT,  SITE VARCHAR(8),  PERSONID INT,  SUBJECTLABEL VARCHAR(50),  VISITID INT,  VISITCYCLENUMBER SMALLINT,  VISITCYCLEDATE DECIMAL(16,10),  CRFPAGEID INT,  CRFPAGECYCLENUMBER SMALLINT,  CRFPAGECYCLEDATE DECIMAL(16,10),  DATAITEMID INT,  REPEATNUMBER SMALLINT,  RESPONSE VARCHAR(255),  USERNAME VARCHAR(20),  UPLOADMESSAGE VARCHAR(255), CONSTRAINT PKBATCHRESPONSEDATA PRIMARY KEY (BATCHRESPONSEID));

CREATE TABLE CRFELEMENT( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  CRFPAGEID INT NOT NULL,  CRFELEMENTID SMALLINT NOT NULL,  DATAITEMID INT,  CONTROLTYPE SMALLINT,  FONTCOLOUR INT,  CAPTION VARCHAR(255),  FONTNAME VARCHAR(50),  FONTBOLD SMALLINT,  FONTITALIC SMALLINT,  FONTSIZE SMALLINT,  FIELDORDER SMALLINT,  SKIPCONDITION VARCHAR(4000),  HEIGHT SMALLINT,  WIDTH SMALLINT,  CAPTIONX INT,  CAPTIONY INT,  X INT,  Y INT,  PRINTORDER INT,  HIDDEN SMALLINT,  LOCALFLAG SMALLINT,  OPTIONAL SMALLINT,  MANDATORY SMALLINT,  REQUIRECOMMENT SMALLINT,  ROLECODE VARCHAR(15),  CLINICALTESTDATEEXPR VARCHAR(2000),  OWNERQGROUPID INT,  QGROUPID INT,  QGROUPFIELDORDER SMALLINT,  SHOWSTATUSFLAG SMALLINT,  CAPTIONFONTNAME VARCHAR(50),  CAPTIONFONTBOLD SMALLINT,  CAPTIONFONTITALIC SMALLINT,  CAPTIONFONTSIZE SMALLINT,  CAPTIONFONTCOLOUR INT,  ELEMENTUSE SMALLINT,  DISPLAYLENGTH SMALLINT,  HOTLINK VARCHAR(2000),  DESCRIPTION VARCHAR(255), CONSTRAINT PKCRFELEMENT PRIMARY KEY (CLINICALTRIALID, CRFPAGEID, CRFELEMENTID, VERSIONID));

CREATE TABLE CRFPAGE( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  CRFPAGEID INT NOT NULL,  CRFTITLE VARCHAR(50),  BACKGROUNDCOLOUR INT,  CRFPAGEORDER SMALLINT,  CRFPAGECODE VARCHAR(15),  COPIEDFROMCLINICALTRIALID INT,  COPIEDFROMVERSIONID SMALLINT,  COPIEDFROMCRFPAGEID INT,  CRFPAGELABEL VARCHAR(255),  LOCALCRFPAGELABEL SMALLINT,  SEQUENTIALENTRY SMALLINT,  CRFPAGEDATELABEL VARCHAR(255),  DISPLAYNUMBERS SMALLINT,  HIDEIFINACTIVE TINYINT,  EFORMDATEPROMPT TINYINT,  EFORMWIDTH INT, CONSTRAINT PKCRFPAGE PRIMARY KEY (CLINICALTRIALID, CRFPAGEID, VERSIONID));

CREATE TABLE CRFPAGEINSTANCE( CLINICALTRIALID INT NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  PERSONID INT NOT NULL,  CRFPAGETASKID INT NOT NULL,  VISITID INT,  CRFPAGEID INT,  VISITCYCLENUMBER SMALLINT,  CRFPAGECYCLENUMBER SMALLINT,  CRFPAGEDATE DECIMAL(16,10),  CRFPAGESTATUS SMALLINT,  CHANGED SMALLINT,  CRFPAGEINSTANCELABEL VARCHAR(255),  LOCKSTATUS TINYINT,  IMPORTTIMESTAMP DECIMAL(16,10),  LABORATORYCODE VARCHAR(15),  DISCREPANCYSTATUS SMALLINT,  SDVSTATUS SMALLINT,  NOTESTATUS SMALLINT,  IMPORTTIMESTAMP_TZ SMALLINT,  SEQUENCEID DECIMAL(15), CONSTRAINT PKCRFPAGEINSTANCE PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID, CRFPAGETASKID));

CREATE TABLE CTC( CTCID INT NOT NULL,  CTCSCHEMECODE VARCHAR(15) NOT NULL,  CLINICALTESTCODE VARCHAR(15),  CTCGRADE SMALLINT,  CTCMIN DECIMAL(16,10),  CTCMAX DECIMAL(16,10),  CTCMINTYPE SMALLINT,  CTCMAXTYPE SMALLINT, CONSTRAINT PKCTC PRIMARY KEY (CTCSCHEMECODE, CTCID));

CREATE TABLE CTCSCHEME( CTCSCHEMECODE VARCHAR(15) NOT NULL,  CTCSCHEMEDESCRIPTION VARCHAR(255), CONSTRAINT PKCTCSCHEME PRIMARY KEY (CTCSCHEMECODE));

CREATE TABLE CLINICALTEST( CLINICALTESTCODE VARCHAR(15) NOT NULL,  CLINICALTESTDESCRIPTION VARCHAR(255),  CLINICALTESTGROUPCODE VARCHAR(15),  UNIT VARCHAR(15), CONSTRAINT PKCLINICALTEST PRIMARY KEY (CLINICALTESTCODE));

CREATE TABLE CLINICALTESTGROUP( CLINICALTESTGROUPCODE VARCHAR(15) NOT NULL,  CLINICALTESTGROUPDESCRIPTION VARCHAR(255), CONSTRAINT PKCLINICALTESTGROUP PRIMARY KEY (CLINICALTESTGROUPCODE));

CREATE TABLE CLINICALTRIAL( CLINICALTRIALID INT NOT NULL,  CLINICALTRIALNAME VARCHAR(15),  CLINICALTRIALDESCRIPTION VARCHAR(255),  PHASEID SMALLINT,  STATUSID SMALLINT,  KEYWORDS VARCHAR(255),  EXPECTEDRECRUITMENT INT,  TRIALTYPEID SMALLINT, CONSTRAINT PKCLINICALTRIAL PRIMARY KEY (CLINICALTRIALID));

CREATE TABLE DATAIMPORT( CLINICALTRIALNAME VARCHAR(15) NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  PERSONID INT NOT NULL,  DATAFILENAME VARCHAR(255) NOT NULL,  LASTLFMESSAGEID INT,  RECEIVEDTIMESTAMP DECIMAL(16,10),  RECEIVEDTIMESTAMP_TZ SMALLINT, CONSTRAINT PKDATAIMPORT PRIMARY KEY (CLINICALTRIALNAME, TRIALSITE, PERSONID, DATAFILENAME));

CREATE TABLE DATAITEM( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  DATAITEMID INT NOT NULL,  DATAITEMCODE VARCHAR(15),  DATAITEMNAME VARCHAR(50),  DATATYPE SMALLINT,  DATAITEMFORMAT VARCHAR(255),  UNITOFMEASUREMENT VARCHAR(15),  DATAITEMLENGTH SMALLINT,  DERIVATION VARCHAR(4000),  DATAITEMHELPTEXT VARCHAR(255),  COPIEDFROMCLINICALTRIALID INT,  COPIEDFROMVERSIONID SMALLINT,  COPIEDFROMDATAITEMID INT,  EXPORTNAME VARCHAR(50),  DATAITEMCASE SMALLINT,  CLINICALTESTCODE VARCHAR(15),  MACROONLY SMALLINT,  DESCRIPTION VARCHAR(255), CONSTRAINT PKDATAITEM PRIMARY KEY (CLINICALTRIALID, DATAITEMID, VERSIONID));

CREATE TABLE DATAITEMRESPONSE( CLINICALTRIALID INT NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  PERSONID INT NOT NULL,  RESPONSETASKID INT NOT NULL,  VISITID INT,  CRFPAGEID INT,  CRFELEMENTID SMALLINT,  DATAITEMID INT,  VISITCYCLENUMBER SMALLINT,  CRFPAGECYCLENUMBER SMALLINT,  CRFPAGETASKID INT,  RESPONSEVALUE VARCHAR(255),  RESPONSETIMESTAMP DECIMAL(16,10),  VALUECODE VARCHAR(15),  USERNAME VARCHAR(20),  UNITOFMEASUREMENT VARCHAR(15),  COMMENTS VARCHAR(255),  RESPONSESTATUS SMALLINT,  CHANGED SMALLINT,  SOFTWAREVERSION VARCHAR(15),  REASONFORCHANGE VARCHAR(255),  LOCKSTATUS TINYINT,  IMPORTTIMESTAMP DECIMAL(16,10),  VALIDATIONID SMALLINT,  VALIDATIONMESSAGE VARCHAR(4000),  OVERRULEREASON VARCHAR(255),  LABRESULT VARCHAR(1),  CTCGRADE SMALLINT,  CLINICALTESTDATE DECIMAL(16,10),  LABORATORYCODE VARCHAR(15),  HADVALUE SMALLINT,  REPEATNUMBER SMALLINT NOT NULL,  CHANGECOUNT SMALLINT,  DISCREPANCYSTATUS SMALLINT,  SDVSTATUS SMALLINT,  NOTESTATUS SMALLINT,  RESPONSETIMESTAMP_TZ SMALLINT,  IMPORTTIMESTAMP_TZ SMALLINT,  DATABASETIMESTAMP DECIMAL(16,10),  DATABASETIMESTAMP_TZ SMALLINT,  SEQUENCEID DECIMAL(15),  STANDARDVALUE DECIMAL(16,10),  USERNAMEFULL VARCHAR(100), CONSTRAINT PKDATAITEMRESPONSE PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID, RESPONSETASKID, REPEATNUMBER));

CREATE TABLE DATAITEMRESPONSEHISTORY( CLINICALTRIALID INT NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  PERSONID INT NOT NULL,  RESPONSETASKID INT NOT NULL,  RESPONSETIMESTAMP DECIMAL(16,10) NOT NULL,  VISITID INT,  CRFPAGEID INT,  CRFELEMENTID SMALLINT,  DATAITEMID INT,  VISITCYCLENUMBER SMALLINT,  CRFPAGECYCLENUMBER SMALLINT,  CRFPAGETASKID INT,  RESPONSEVALUE VARCHAR(255),  VALUECODE VARCHAR(15),  USERNAME VARCHAR(20),  UNITOFMEASUREMENT VARCHAR(15),  COMMENTS VARCHAR(255),  RESPONSESTATUS SMALLINT,  CHANGED SMALLINT,  SOFTWAREVERSION VARCHAR(15),  REASONFORCHANGE VARCHAR(255),  LOCKSTATUS TINYINT,  IMPORTTIMESTAMP DECIMAL(16,10),  VALIDATIONID SMALLINT,  VALIDATIONMESSAGE VARCHAR(4000),  OVERRULEREASON VARCHAR(255),  LABRESULT VARCHAR(1),  CTCGRADE SMALLINT,  CLINICALTESTDATE DECIMAL(16,10),  LABORATORYCODE VARCHAR(15),  HADVALUE SMALLINT,  REPEATNUMBER SMALLINT NOT NULL,  RESPONSETIMESTAMP_TZ SMALLINT,  IMPORTTIMESTAMP_TZ SMALLINT,  DATABASETIMESTAMP DECIMAL(16,10),  DATABASETIMESTAMP_TZ SMALLINT,  SEQUENCEID DECIMAL(15),  STANDARDVALUE DECIMAL(16,10),  USERNAMEFULL VARCHAR(100), CONSTRAINT PKDATAITEMRESPONSEHISTORY PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID, RESPONSETASKID, RESPONSETIMESTAMP, REPEATNUMBER));

CREATE TABLE DATAITEMVALIDATION( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  DATAITEMID INT NOT NULL,  VALIDATIONID SMALLINT NOT NULL,  VALIDATIONTYPEID SMALLINT,  DATAITEMVALIDATION VARCHAR(4000),  VALIDATIONMESSAGE VARCHAR(4000), CONSTRAINT PKDATAITEMVALIDATION PRIMARY KEY (CLINICALTRIALID, DATAITEMID, VALIDATIONID, VERSIONID));

CREATE TABLE DATATYPE( DATATYPEID INT NOT NULL,  DATATYPENAME VARCHAR(15), CONSTRAINT PKDATATYPE PRIMARY KEY (DATATYPEID));

CREATE TABLE EFORMQGROUP( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  CRFPAGEID INT NOT NULL,  QGROUPID INT NOT NULL,  BORDER SMALLINT,  DISPLAYROWS SMALLINT,  INITIALROWS SMALLINT,  MINREPEATS SMALLINT,  MAXREPEATS SMALLINT, CONSTRAINT PKEFORMQUESTIONGROUP PRIMARY KEY (CLINICALTRIALID, VERSIONID, CRFPAGEID, QGROUPID));

CREATE TABLE ELIGIBILITY( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  ELIGIBILITYCODE VARCHAR(15) NOT NULL,  RANDOMISATIONCODE VARCHAR(15),  FLAG SMALLINT,  CONDITION VARCHAR(4000), CONSTRAINT PKELIGIBILITY PRIMARY KEY (CLINICALTRIALID, ELIGIBILITYCODE, VERSIONID));

CREATE TABLE KEYWORD( KEYWORD VARCHAR(50) NOT NULL, CONSTRAINT PKKEYWORD PRIMARY KEY (KEYWORD));

CREATE TABLE LFMESSAGE( CLINICALTRIALNAME VARCHAR(15) NOT NULL,  CLINICALTRIALID INT NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  PERSONID INT NOT NULL,  SOURCE SMALLINT NOT NULL,  MESSAGEID INT NOT NULL,  SCOPE SMALLINT,  VISITID INT,  VISITCYCLENUMBER SMALLINT,  CRFPAGEID INT,  CRFPAGECYCLENUMBER SMALLINT,  RESPONSETASKID INT,  REPEATNUMBER SMALLINT,  DATAITEMID INT,  USERNAME VARCHAR(20),  USERNAMEFULL VARCHAR(100),  MSGTYPE SMALLINT,  ROLLBACKSOURCE SMALLINT,  ROLLBACKMESSAGEID INT,  PROCESSEDSTATUS SMALLINT,  MSGCREATEDTIMESTAMP DECIMAL(16,10),  MSGCREATEDTIMESTAMP_TZ SMALLINT,  PROCESSEDTIMESTAMP DECIMAL(16,10),  PROCESSEDTIMESTAMP_TZ SMALLINT,  SENTTIMESTAMP DECIMAL(16,10),  SENTTIMESTAMP_TZ SMALLINT,  RECEIVEDTIMESTAMP DECIMAL(16,10),  RECEIVEDTIMESTAMP_TZ SMALLINT,  SEQUENCENO INT, CONSTRAINT PKLFMESSAGE PRIMARY KEY (CLINICALTRIALNAME, CLINICALTRIALID, TRIALSITE, PERSONID, SOURCE, MESSAGEID));

CREATE TABLE LABORATORY( LABORATORYCODE VARCHAR(15) NOT NULL,  LABORATORYDESCRIPTION VARCHAR(255),  SITE VARCHAR(8),  CHANGED SMALLINT, CONSTRAINT PKLABORATORY PRIMARY KEY (LABORATORYCODE));

CREATE TABLE LOGDETAILS( LOGDATETIME DECIMAL(16,10) NOT NULL,  LOGNUMBER INT NOT NULL,  TASKID VARCHAR(50) NOT NULL,  LOGMESSAGE VARCHAR(255),  USERNAME VARCHAR(20),  LOGDATETIME_TZ SMALLINT,  LOCATION VARCHAR(50) NOT NULL,  STATUS SMALLINT, CONSTRAINT PKLOGDETAILS PRIMARY KEY (LOGDATETIME, LOGNUMBER, TASKID, LOCATION));

CREATE TABLE MACROCONTROL( MACROVERSION VARCHAR(15),  BUILDSUBVERSION VARCHAR(10),  IDLETIMEOUT SMALLINT);

CREATE TABLE MACROCOUNTRY( COUNTRYID SMALLINT NOT NULL,  COUNTRYDESCRIPTION VARCHAR(50), CONSTRAINT PKMACROCOUNTRY PRIMARY KEY (COUNTRYID));

CREATE TABLE MACRODBSETTING( SETTINGSECTION VARCHAR(15) NOT NULL,  SETTINGKEY VARCHAR(15) NOT NULL,  SETTINGVALUE VARCHAR(15), CONSTRAINT PKMACRODBSETTING PRIMARY KEY (SETTINGSECTION, SETTINGKEY));

CREATE TABLE MACROLOCK( STUDYID INT NOT NULL,  SITE VARCHAR(8) NOT NULL,  SUBJECTID INT NOT NULL,  EFORMINSTANCEID INT NOT NULL,  USERNAME VARCHAR(20),  LOCKTIMESTAMP DECIMAL(16,10),  TOKEN VARCHAR(10), CONSTRAINT PKMACROLOCK PRIMARY KEY (STUDYID, SITE, SUBJECTID, EFORMINSTANCEID));

CREATE TABLE MACROTABLE( TABLENAME VARCHAR(30) NOT NULL,  SEGMENTID VARCHAR(3),  STYDEF SMALLINT,  PATRSP SMALLINT,  LABDEF SMALLINT, CONSTRAINT PKMACROTABLE PRIMARY KEY (TABLENAME));

CREATE TABLE MACROUSERSETTINGS( USERNAME VARCHAR(20) NOT NULL,  USERSETTING VARCHAR(20) NOT NULL,  SETTINGVALUE VARCHAR(50) NOT NULL, CONSTRAINT PKMACROUSERSETTING PRIMARY KEY (USERNAME, USERSETTING, SETTINGVALUE));

CREATE TABLE MIMESSAGE( MIMESSAGEID INT NOT NULL,  MIMESSAGESITE VARCHAR(8) NOT NULL,  MIMESSAGESOURCE SMALLINT NOT NULL,  MIMESSAGETYPE SMALLINT,  MIMESSAGESCOPE SMALLINT,  MIMESSAGEOBJECTID INT,  MIMESSAGEOBJECTSOURCE SMALLINT,  MIMESSAGEPRIORITY SMALLINT,  MIMESSAGETRIALNAME VARCHAR(15),  MIMESSAGEPERSONID INT,  MIMESSAGEVISITID INT,  MIMESSAGEVISITCYCLE SMALLINT,  MIMESSAGECRFPAGETASKID INT,  MIMESSAGERESPONSETASKID INT,  MIMESSAGERESPONSEVALUE VARCHAR(255),  MIMESSAGEOCDISCREPANCYID INT,  MIMESSAGECREATED DECIMAL(16,10),  MIMESSAGESENT DECIMAL(16,10),  MIMESSAGERECEIVED DECIMAL(16,10),  MIMESSAGEHISTORY SMALLINT,  MIMESSAGEPROCESSED SMALLINT,  MIMESSAGESTATUS SMALLINT,  MIMESSAGETEXT VARCHAR(2000),  MIMESSAGEUSERNAME VARCHAR(20),  MIMESSAGEUSERNAMEFULL VARCHAR(100),  MIMESSAGERESPONSETIMESTAMP DECIMAL(16,10),  MIMESSAGERESPONSECYCLE SMALLINT,  MIMESSAGECREATED_TZ SMALLINT,  MIMESSAGESENT_TZ SMALLINT,  MIMESSAGERECEIVED_TZ SMALLINT,  SEQUENCEID DECIMAL(15),  MIMESSAGECRFPAGEID INT,  MIMESSAGECRFPAGECYCLE SMALLINT,  MIMESSAGEDATAITEMID INT, CONSTRAINT PKMIMESSAGE PRIMARY KEY (MIMESSAGEID, MIMESSAGESITE, MIMESSAGESOURCE));

CREATE TABLE MESSAGE( TRIALSITE VARCHAR(8) NOT NULL,  CLINICALTRIALID INT,  MESSAGETYPE SMALLINT,  MESSAGETIMESTAMP DECIMAL(16,10),  USERNAME VARCHAR(20),  MESSAGEBODY VARCHAR(255),  MESSAGEPARAMETERS VARCHAR(3000),  MESSAGERECEIVED SMALLINT,  MESSAGEDIRECTION SMALLINT NOT NULL,  MESSAGEID INT NOT NULL,  MESSAGERECEIVEDTIMESTAMP DECIMAL(16,10),  MESSAGETIMESTAMP_TZ SMALLINT,  MESSAGERECEIVEDTIMESTAMP_TZ SMALLINT, CONSTRAINT PKMESSAGE PRIMARY KEY (TRIALSITE, MESSAGEID, MESSAGEDIRECTION));

CREATE TABLE NEWDBCOLUMN( VERSIONMAJOR SMALLINT NOT NULL,  VERSIONMINOR SMALLINT NOT NULL,  VERSIONREVISION SMALLINT NOT NULL,  TABLENAME VARCHAR(30) NOT NULL,  COLUMNNAME VARCHAR(30) NOT NULL,  COLUMNORDER SMALLINT,  DEFAULTVALUE VARCHAR(255),  CHANGETYPE VARCHAR(15),  COLUMNNUMBER SMALLINT, CONSTRAINT PKNEWDBCOLUMN PRIMARY KEY (VERSIONMAJOR, VERSIONMINOR, VERSIONREVISION, TABLENAME, COLUMNNAME));

CREATE TABLE NORMALRANGE( NORMALRANGEID INT NOT NULL,  LABORATORYCODE VARCHAR(15) NOT NULL,  CLINICALTESTCODE VARCHAR(15),  NORMALRANGEGENDER SMALLINT,  NORMALRANGEAGEMIN SMALLINT,  NORMALRANGEAGEMAX SMALLINT,  NORMALRANGEEFFECTIVESTART DECIMAL(16,10),  NORMALRANGEEFFECTIVEEND DECIMAL(16,10),  NORMALRANGENORMALMIN DECIMAL(16,10),  NORMALRANGENORMALMAX DECIMAL(16,10),  NORMALRANGEFEASIBLEMIN DECIMAL(16,10),  NORMALRANGEFEASIBLEMAX DECIMAL(16,10),  NORMALRANGEABSOLUTEMIN DECIMAL(16,10),  NORMALRANGEABSOLUTEMAX DECIMAL(16,10),  NORMALRANGEPERCENT SMALLINT, CONSTRAINT PKNORMALRANGE PRIMARY KEY (LABORATORYCODE, NORMALRANGEID));

CREATE TABLE PROTOCOLS( FILENAME VARCHAR(50) NOT NULL,  PROTOCOLNAME VARCHAR(50),  VERSION VARCHAR(50),  DESCRIPTION VARCHAR(2000),  AUTHOR VARCHAR(50),  CREATED DECIMAL(16,10),  MODIFIED DECIMAL(16,10),  AREZZOVERSION VARCHAR(50),  INUSE SMALLINT,  AREZZOFILE TEXT, CONSTRAINT PKPROTOCOLS PRIMARY KEY (FILENAME));

CREATE TABLE QGROUP( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  QGROUPID INT NOT NULL,  QGROUPCODE VARCHAR(15),  QGROUPNAME VARCHAR(255),  DISPLAYTYPE SMALLINT, CONSTRAINT PKQGROUP PRIMARY KEY (CLINICALTRIALID, VERSIONID, QGROUPID));

CREATE TABLE QGROUPQUESTION( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  QGROUPID INT NOT NULL,  DATAITEMID INT NOT NULL,  QORDER SMALLINT, CONSTRAINT PKQGROUPQUESTION PRIMARY KEY (CLINICALTRIALID, VERSIONID, QGROUPID, DATAITEMID));

CREATE TABLE RSNEXTNUMBER( CLINICALTRIALNAME VARCHAR(15) NOT NULL,  NEXTNUMBERID INT NOT NULL,  PREFIX VARCHAR(255),  SUFFIX VARCHAR(255),  NEXTNUMBER INT, CONSTRAINT PKRSNEXTNUMBER PRIMARY KEY (CLINICALTRIALNAME, NEXTNUMBERID));

CREATE TABLE RSSUBJECTIDENTIFIER( CLINICALTRIALNAME VARCHAR(15) NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  PERSONID INT NOT NULL,  SUBJECTIDENTIFIER VARCHAR(255), CONSTRAINT PKRSSUBJECTIDENTIFIER PRIMARY KEY (CLINICALTRIALNAME, TRIALSITE, PERSONID));

CREATE TABLE RSUNIQUENESSCHECK( CLINICALTRIALNAME VARCHAR(15) NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  PERSONID INT NOT NULL,  CHECKCODE VARCHAR(15) NOT NULL,  CHECKVALUE VARCHAR(255),  CHECKTIMESTAMP DECIMAL(16,10),  CHECKTIMESTAMP_TZ SMALLINT, CONSTRAINT PKRSUNIQUENESSCHECK PRIMARY KEY (CLINICALTRIALNAME, TRIALSITE, PERSONID, CHECKCODE));

CREATE TABLE REASONFORCHANGE( CLINICALTRIALID INT,  VERSIONID SMALLINT,  REASONFORCHANGEID SMALLINT,  REASONFORCHANGE VARCHAR(255),  REASONTYPE SMALLINT);

CREATE TABLE REQUIREDDATA( DATAITEMID INT NOT NULL,  TRIALTYPEID SMALLINT NOT NULL, CONSTRAINT PKREQUIREDDATA PRIMARY KEY (DATAITEMID, TRIALTYPEID));

CREATE TABLE SITE( SITE VARCHAR(8) NOT NULL,  SITEDESCRIPTION VARCHAR(255),  SITESTATUS SMALLINT,  SITELOCATION SMALLINT,  SITECOUNTRY SMALLINT, CONSTRAINT PKSITE PRIMARY KEY (SITE));

CREATE TABLE SITELABORATORY( SITE VARCHAR(8) NOT NULL,  LABORATORYCODE VARCHAR(15) NOT NULL, CONSTRAINT PKSITELABORATORY PRIMARY KEY (SITE, LABORATORYCODE));

CREATE TABLE STANDARDDATAFORMAT( STANDARDDATAFORMATID SMALLINT NOT NULL,  DATAFORMAT VARCHAR(255),  DATATYPEID SMALLINT, CONSTRAINT PKSTANDARDDATAFORMAT PRIMARY KEY (STANDARDDATAFORMATID));

CREATE TABLE STUDYDEFINITION( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  DEFAULTFONTCOLOUR INT,  DEFAULTCRFPAGECOLOUR INT,  DEFAULTFONTNAME VARCHAR(50),  DEFAULTFONTBOLD SMALLINT,  DEFAULTFONTITALIC SMALLINT,  DEFAULTFONTSIZE SMALLINT,  USERNAME VARCHAR(20),  STUDYDEFINITIONTIMESTAMP DECIMAL(16,10),  TRIALSUBJECTLABEL VARCHAR(255),  LOCALTRIALSUBJECTLABEL SMALLINT,  STANDARDDATEFORMAT VARCHAR(50),  STANDARDTIMEFORMAT VARCHAR(50),  SINGLEUSEDATAITEMS SMALLINT,  CTCSCHEMECODE VARCHAR(15),  DOBEXPR VARCHAR(4000),  GENDEREXPR VARCHAR(4000),  RRSERVERTYPE SMALLINT,  RRHTTPADDRESS VARCHAR(255),  RRUSERNAME VARCHAR(20),  RRPASSWORD VARCHAR(50),  RRPROXYSERVER VARCHAR(255),  AREZZOUPDATESTATUS SMALLINT,  AREZZOMEMORY VARCHAR(100), CONSTRAINT PKSTUDYDEFINITION PRIMARY KEY (CLINICALTRIALID, VERSIONID));

CREATE TABLE STUDYDOCUMENT( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  DOCUMENTID SMALLINT NOT NULL,  DOCUMENTPATH VARCHAR(255), CONSTRAINT PKSTUDYDOCUMENT PRIMARY KEY (CLINICALTRIALID, DOCUMENTID, VERSIONID));

CREATE TABLE STUDYREPORT( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  REPORTID SMALLINT NOT NULL,  REPORTNAME VARCHAR(255),  REPORTTYPE SMALLINT,  AUTOMATICNUMBERING SMALLINT, CONSTRAINT PKSTUDYREPORT PRIMARY KEY (CLINICALTRIALID, REPORTID, VERSIONID));

CREATE TABLE STUDYREPORTDATA( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  REPORTID SMALLINT NOT NULL,  REPORTLINEID SMALLINT NOT NULL,  SEGMENTID INT NOT NULL,  SEQUENCENUMBER INT,  VISITID INT,  CRFPAGEID INT,  DATAITEMID INT,  CRFELEMENTID SMALLINT,  SEGMENTTEXT VARCHAR(255), CONSTRAINT PKSTUDYREPORTDATA PRIMARY KEY (CLINICALTRIALID, REPORTID, REPORTLINEID, SEGMENTID, VERSIONID));

CREATE TABLE STUDYVERSION( CLINICALTRIALID INT NOT NULL,  STUDYVERSION SMALLINT NOT NULL,  VERSIONTIMESTAMP DECIMAL(16,10),  VERSIONDESCRIPTION VARCHAR(255),  VERSIONTIMESTAMP_TZ SMALLINT, CONSTRAINT PKSTUDYVERSION PRIMARY KEY (CLINICALTRIALID, STUDYVERSION));

CREATE TABLE STUDYVISIT( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  VISITID INT NOT NULL,  VISITNAME VARCHAR(50),  VISITORDER SMALLINT,  VISITCODE VARCHAR(15),  VISITDATELABEL VARCHAR(255),  VISITBACKGROUNDCOLOUR INT,  VISITDATEPROMPT TINYINT,  REPEATING SMALLINT, CONSTRAINT PKSTUDYVISIT PRIMARY KEY (CLINICALTRIALID, VISITID, VERSIONID));

CREATE TABLE STUDYVISITCRFPAGE( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  VISITID INT NOT NULL,  CRFPAGEID INT NOT NULL,  REPEATING SMALLINT,  EFORMUSE SMALLINT, CONSTRAINT PKSTUDYVISITCRFPAGE PRIMARY KEY (CLINICALTRIALID, VISITID, CRFPAGEID, VERSIONID));

CREATE TABLE SUBJECTNUMBERING( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  STARTNUMBER INT,  NUMBERWIDTH SMALLINT,  PREFIX VARCHAR(4000),  USEPREFIX SMALLINT,  SUFFIX VARCHAR(4000),  USESUFFIX SMALLINT,  TRIGGERVISITID INT,  TRIGGERFORMID INT,  USEREGISTRATION SMALLINT, CONSTRAINT PKSUBJECTNUMBERING PRIMARY KEY (CLINICALTRIALID, VERSIONID));

CREATE TABLE TRIALOFFICE( TRIALOFFICE VARCHAR(50) NOT NULL,  EFFECTIVEFROM DECIMAL(16,10) NOT NULL,  EFFECTIVETO DECIMAL(16,10) NOT NULL,  HTTPADDRESS VARCHAR(255),  SITE VARCHAR(8),  TRANSFERDATA SMALLINT,  USERNAME VARCHAR(50),  USERPASSWORD VARCHAR(50),  PORTNUMBER SMALLINT,  PROXYSERVER VARCHAR(255), CONSTRAINT PKTRIALOFFICE PRIMARY KEY (TRIALOFFICE, EFFECTIVEFROM, EFFECTIVETO));

CREATE TABLE TRIALPHASE( PHASEID SMALLINT NOT NULL,  PHASENAME VARCHAR(50), CONSTRAINT PKTRIALPHASE PRIMARY KEY (PHASEID));

CREATE TABLE TRIALSITE( CLINICALTRIALID INT NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  STUDYVERSION SMALLINT, CONSTRAINT PKTRIALSITE PRIMARY KEY (CLINICALTRIALID, TRIALSITE));

CREATE TABLE TRIALSTATUS( STATUSID SMALLINT NOT NULL,  STATUSNAME VARCHAR(50), CONSTRAINT PKTRIALSTATUS PRIMARY KEY (STATUSID));

CREATE TABLE TRIALSTATUSHISTORY( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  TRIALSTATUSCHANGEID SMALLINT NOT NULL,  STATUSID SMALLINT,  USERNAME VARCHAR(20),  STATUSCHANGEDTIMESTAMP DECIMAL(16,10),  STATUSCHANGEDTIMESTAMP_TZ SMALLINT, CONSTRAINT PKTRIALSTATUSHISTORY PRIMARY KEY (CLINICALTRIALID, TRIALSTATUSCHANGEID, VERSIONID));

CREATE TABLE TRIALSUBJECT( CLINICALTRIALID INT NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  PERSONID INT NOT NULL,  DATEOFBIRTH DECIMAL(16,10),  GENDER VARCHAR(1),  LOCALIDENTIFIER1 VARCHAR(50),  LOCALIDENTIFIER2 VARCHAR(50),  PROFORMASTATE TEXT,  TRIALSUBJECTSTATUS SMALLINT,  CHANGED SMALLINT,  LOCKSTATUS TINYINT,  IMPORTTIMESTAMP DECIMAL(16,10),  SUBJECTGENDER SMALLINT,  REGISTRATIONSTATUS SMALLINT,  DISCREPANCYSTATUS SMALLINT,  SDVSTATUS SMALLINT,  NOTESTATUS SMALLINT,  IMPORTTIMESTAMP_TZ SMALLINT,  SEQUENCEID DECIMAL(15),  SUBJECTTIMESTAMP DECIMAL(16,10),  SUBJECTTIMESTAMP_TZ SMALLINT, CONSTRAINT PKTRIALSUBJECT PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID));

CREATE TABLE TRIALTYPE( TRIALTYPEID SMALLINT NOT NULL,  TRIALTYPENAME VARCHAR(50), CONSTRAINT PKTRIALTYPE PRIMARY KEY (TRIALTYPEID));

CREATE TABLE UNIQUENESSCHECK( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  CHECKCODE VARCHAR(15) NOT NULL,  EXPRESSION VARCHAR(4000), CONSTRAINT PKUNIQUENESSCHECK PRIMARY KEY (CLINICALTRIALID, CHECKCODE, VERSIONID));

CREATE TABLE UNITCLASSES( UNITCLASS VARCHAR(50) NOT NULL, CONSTRAINT PKUNITCLASSES PRIMARY KEY (UNITCLASS));

CREATE TABLE UNITCONVERSIONFACTORS( FROMUNIT VARCHAR(15) NOT NULL,  TOUNIT VARCHAR(15) NOT NULL,  CONVERSIONFACTOR DECIMAL(16,10),  UNITCLASS VARCHAR(50), CONSTRAINT PKUNITCONVERSIONFACTORS PRIMARY KEY (FROMUNIT, TOUNIT));

CREATE TABLE UNITS( UNIT VARCHAR(15) NOT NULL,  UNITCLASS VARCHAR(50), CONSTRAINT PKUNITS PRIMARY KEY (UNIT));

CREATE TABLE USERROLE( USERNAME VARCHAR(20) NOT NULL,  ROLECODE VARCHAR(15) NOT NULL,  STUDYCODE VARCHAR(50) NOT NULL,  SITECODE VARCHAR(50) NOT NULL,  TYPEOFINSTALLATION SMALLINT NOT NULL, CONSTRAINT PKUSERROLE PRIMARY KEY (USERNAME, ROLECODE, STUDYCODE, SITECODE, TYPEOFINSTALLATION));

CREATE TABLE VALIDATIONACTION( VALIDATIONACTIONID SMALLINT NOT NULL,  VALIDATIONACTIONNAME VARCHAR(15), CONSTRAINT PKVALIDATIONACTION PRIMARY KEY (VALIDATIONACTIONID));

CREATE TABLE VALIDATIONTYPE( VALIDATIONTYPEID SMALLINT NOT NULL,  VALIDATIONTYPENAME VARCHAR(50),  VALIDATIONACTIONID SMALLINT, CONSTRAINT PKVALIDATIONTYPE PRIMARY KEY (VALIDATIONTYPEID));

CREATE TABLE VALUEDATA( CLINICALTRIALID INT NOT NULL,  VERSIONID SMALLINT NOT NULL,  DATAITEMID INT NOT NULL,  VALUEID SMALLINT NOT NULL,  VALUECODE VARCHAR(15),  ITEMVALUE VARCHAR(255),  ACTIVE SMALLINT,  VALUEORDER SMALLINT, CONSTRAINT PKVALUEDATA PRIMARY KEY (CLINICALTRIALID, DATAITEMID, VALUEID, VERSIONID));

CREATE TABLE VISITINSTANCE( CLINICALTRIALID INT NOT NULL,  TRIALSITE VARCHAR(8) NOT NULL,  PERSONID INT NOT NULL,  VISITTASKID INT NOT NULL,  VISITID INT,  VISITCYCLENUMBER SMALLINT,  VISITDATE DECIMAL(16,10),  VISITSTATUS SMALLINT,  CHANGED SMALLINT,  LOCKSTATUS TINYINT,  IMPORTTIMESTAMP DECIMAL(16,10),  DISCREPANCYSTATUS SMALLINT,  SDVSTATUS SMALLINT,  NOTESTATUS SMALLINT,  IMPORTTIMESTAMP_TZ SMALLINT,  SEQUENCEID DECIMAL(15), CONSTRAINT PKVISITINSTANCE PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID, VISITTASKID));


