CREATE TABLE AREZZOTOKEN( AREZZOID VARCHAR2(50) NOT NULL,  DBTOKEN NUMBER(11),  CLINICALTRIALID NUMBER(11),  TRIALSITE VARCHAR2(8),  PERSONID NUMBER(11), CONSTRAINT PKAREZZOTOKEN PRIMARY KEY (AREZZOID));

CREATE TABLE AUTOIMPORTCONTROL( UPLOADORDER NUMBER(6) NOT NULL,  STARTSTOP VARCHAR2(10),  WAITINTERVAL NUMBER(11), CONSTRAINT PKUPLOADORDER PRIMARY KEY (UPLOADORDER));

CREATE TABLE BATCHRESPONSEDATA( BATCHRESPONSEID NUMBER(11) NOT NULL,  CLINICALTRIALID NUMBER(11),  SITE VARCHAR2(8),  PERSONID NUMBER(11),  SUBJECTLABEL VARCHAR2(50),  VISITID NUMBER(11),  VISITCYCLENUMBER NUMBER(6),  VISITCYCLEDATE NUMBER(16,10),  CRFPAGEID NUMBER(11),  CRFPAGECYCLENUMBER NUMBER(6),  CRFPAGECYCLEDATE NUMBER(16,10),  DATAITEMID NUMBER(11),  REPEATNUMBER NUMBER(6),  RESPONSE VARCHAR2(255),  USERNAME VARCHAR2(20),  UPLOADMESSAGE VARCHAR2(255), CONSTRAINT PKBATCHRESPONSEDATA PRIMARY KEY (BATCHRESPONSEID));

CREATE TABLE CRFELEMENT( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  CRFPAGEID NUMBER(11) NOT NULL,  CRFELEMENTID NUMBER(6) NOT NULL,  DATAITEMID NUMBER(11),  CONTROLTYPE NUMBER(6),  FONTCOLOUR NUMBER(11),  CAPTION VARCHAR2(255),  FONTNAME VARCHAR2(50),  FONTBOLD NUMBER(6),  FONTITALIC NUMBER(6),  FONTSIZE NUMBER(6),  FIELDORDER NUMBER(6),  SKIPCONDITION VARCHAR2(4000),  HEIGHT NUMBER(6),  WIDTH NUMBER(6),  CAPTIONX NUMBER(11),  CAPTIONY NUMBER(11),  X NUMBER(11),  Y NUMBER(11),  PRINTORDER NUMBER(11),  HIDDEN NUMBER(6),  LOCALFLAG NUMBER(6),  OPTIONAL NUMBER(6),  MANDATORY NUMBER(6),  REQUIRECOMMENT NUMBER(6),  ROLECODE VARCHAR2(15),  CLINICALTESTDATEEXPR VARCHAR2(2000),  OWNERQGROUPID NUMBER(11),  QGROUPID NUMBER(11),  QGROUPFIELDORDER NUMBER(6),  SHOWSTATUSFLAG NUMBER(6),  CAPTIONFONTNAME VARCHAR2(50),  CAPTIONFONTBOLD NUMBER(6),  CAPTIONFONTITALIC NUMBER(6),  CAPTIONFONTSIZE NUMBER(6),  CAPTIONFONTCOLOUR NUMBER(11),  ELEMENTUSE NUMBER(6),  DISPLAYLENGTH NUMBER(6),  HOTLINK VARCHAR2(2000),  DESCRIPTION VARCHAR2(255), CONSTRAINT PKCRFELEMENT PRIMARY KEY (CLINICALTRIALID, CRFPAGEID, CRFELEMENTID, VERSIONID));

CREATE TABLE CRFPAGE( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  CRFPAGEID NUMBER(11) NOT NULL,  CRFTITLE VARCHAR2(50),  BACKGROUNDCOLOUR NUMBER(11),  CRFPAGEORDER NUMBER(6),  CRFPAGECODE VARCHAR2(15),  COPIEDFROMCLINICALTRIALID NUMBER(11),  COPIEDFROMVERSIONID NUMBER(6),  COPIEDFROMCRFPAGEID NUMBER(11),  CRFPAGELABEL VARCHAR2(255),  LOCALCRFPAGELABEL NUMBER(6),  SEQUENTIALENTRY NUMBER(6),  CRFPAGEDATELABEL VARCHAR2(255),  DISPLAYNUMBERS NUMBER(6),  HIDEIFINACTIVE NUMBER(3),  EFORMDATEPROMPT NUMBER(3),  EFORMWIDTH NUMBER(11), CONSTRAINT PKCRFPAGE PRIMARY KEY (CLINICALTRIALID, CRFPAGEID, VERSIONID));

CREATE TABLE CRFPAGEINSTANCE( CLINICALTRIALID NUMBER(11) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  PERSONID NUMBER(11) NOT NULL,  CRFPAGETASKID NUMBER(11) NOT NULL,  VISITID NUMBER(11),  CRFPAGEID NUMBER(11),  VISITCYCLENUMBER NUMBER(6),  CRFPAGECYCLENUMBER NUMBER(6),  CRFPAGEDATE NUMBER(16,10),  CRFPAGESTATUS NUMBER(6),  CHANGED NUMBER(6),  CRFPAGEINSTANCELABEL VARCHAR2(255),  LOCKSTATUS NUMBER(3),  IMPORTTIMESTAMP NUMBER(16,10),  LABORATORYCODE VARCHAR2(15),  DISCREPANCYSTATUS NUMBER(6),  SDVSTATUS NUMBER(6),  NOTESTATUS NUMBER(6),  IMPORTTIMESTAMP_TZ NUMBER(6),  SEQUENCEID NUMBER(15), CONSTRAINT PKCRFPAGEINSTANCE PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID, CRFPAGETASKID));

CREATE TABLE CTC( CTCID NUMBER(11) NOT NULL,  CTCSCHEMECODE VARCHAR2(15) NOT NULL,  CLINICALTESTCODE VARCHAR2(15),  CTCGRADE NUMBER(6),  CTCMIN NUMBER(16,10),  CTCMAX NUMBER(16,10),  CTCMINTYPE NUMBER(6),  CTCMAXTYPE NUMBER(6), CONSTRAINT PKCTC PRIMARY KEY (CTCSCHEMECODE, CTCID));

CREATE TABLE CTCSCHEME( CTCSCHEMECODE VARCHAR2(15) NOT NULL,  CTCSCHEMEDESCRIPTION VARCHAR2(255), CONSTRAINT PKCTCSCHEME PRIMARY KEY (CTCSCHEMECODE));

CREATE TABLE CLINICALTEST( CLINICALTESTCODE VARCHAR2(15) NOT NULL,  CLINICALTESTDESCRIPTION VARCHAR2(255),  CLINICALTESTGROUPCODE VARCHAR2(15),  UNIT VARCHAR2(15), CONSTRAINT PKCLINICALTEST PRIMARY KEY (CLINICALTESTCODE));

CREATE TABLE CLINICALTESTGROUP( CLINICALTESTGROUPCODE VARCHAR2(15) NOT NULL,  CLINICALTESTGROUPDESCRIPTION VARCHAR2(255), CONSTRAINT PKCLINICALTESTGROUP PRIMARY KEY (CLINICALTESTGROUPCODE));

CREATE TABLE CLINICALTRIAL( CLINICALTRIALID NUMBER(11) NOT NULL,  CLINICALTRIALNAME VARCHAR2(15),  CLINICALTRIALDESCRIPTION VARCHAR2(255),  PHASEID NUMBER(6),  STATUSID NUMBER(6),  KEYWORDS VARCHAR2(255),  EXPECTEDRECRUITMENT NUMBER(11),  TRIALTYPEID NUMBER(6), CONSTRAINT PKCLINICALTRIAL PRIMARY KEY (CLINICALTRIALID));

CREATE TABLE DATAIMPORT( CLINICALTRIALNAME VARCHAR2(15) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  PERSONID NUMBER(11) NOT NULL,  DATAFILENAME VARCHAR2(255) NOT NULL,  LASTLFMESSAGEID NUMBER(11),  RECEIVEDTIMESTAMP NUMBER(16,10),  RECEIVEDTIMESTAMP_TZ NUMBER(6), CONSTRAINT PKDATAIMPORT PRIMARY KEY (CLINICALTRIALNAME, TRIALSITE, PERSONID, DATAFILENAME));

CREATE TABLE DATAITEM( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  DATAITEMID NUMBER(11) NOT NULL,  DATAITEMCODE VARCHAR2(15),  DATAITEMNAME VARCHAR2(50),  DATATYPE NUMBER(6),  DATAITEMFORMAT VARCHAR2(255),  UNITOFMEASUREMENT VARCHAR2(15),  DATAITEMLENGTH NUMBER(6),  DERIVATION VARCHAR2(4000),  DATAITEMHELPTEXT VARCHAR2(255),  COPIEDFROMCLINICALTRIALID NUMBER(11),  COPIEDFROMVERSIONID NUMBER(6),  COPIEDFROMDATAITEMID NUMBER(11),  EXPORTNAME VARCHAR2(50),  DATAITEMCASE NUMBER(6),  CLINICALTESTCODE VARCHAR2(15),  MACROONLY NUMBER(6),  DESCRIPTION VARCHAR2(255), CONSTRAINT PKDATAITEM PRIMARY KEY (CLINICALTRIALID, DATAITEMID, VERSIONID));

CREATE TABLE DATAITEMRESPONSE( CLINICALTRIALID NUMBER(11) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  PERSONID NUMBER(11) NOT NULL,  RESPONSETASKID NUMBER(11) NOT NULL,  VISITID NUMBER(11),  CRFPAGEID NUMBER(11),  CRFELEMENTID NUMBER(6),  DATAITEMID NUMBER(11),  VISITCYCLENUMBER NUMBER(6),  CRFPAGECYCLENUMBER NUMBER(6),  CRFPAGETASKID NUMBER(11),  RESPONSEVALUE VARCHAR2(255),  RESPONSETIMESTAMP NUMBER(16,10),  VALUECODE VARCHAR2(15),  USERNAME VARCHAR2(20),  UNITOFMEASUREMENT VARCHAR2(15),  COMMENTS VARCHAR2(255),  RESPONSESTATUS NUMBER(6),  CHANGED NUMBER(6),  SOFTWAREVERSION VARCHAR2(15),  REASONFORCHANGE VARCHAR2(255),  LOCKSTATUS NUMBER(3),  IMPORTTIMESTAMP NUMBER(16,10),  VALIDATIONID NUMBER(6),  VALIDATIONMESSAGE VARCHAR2(4000),  OVERRULEREASON VARCHAR2(255),  LABRESULT VARCHAR2(1),  CTCGRADE NUMBER(6),  CLINICALTESTDATE NUMBER(16,10),  LABORATORYCODE VARCHAR2(15),  HADVALUE NUMBER(6),  REPEATNUMBER NUMBER(6) NOT NULL,  CHANGECOUNT NUMBER(6),  DISCREPANCYSTATUS NUMBER(6),  SDVSTATUS NUMBER(6),  NOTESTATUS NUMBER(6),  RESPONSETIMESTAMP_TZ NUMBER(6),  IMPORTTIMESTAMP_TZ NUMBER(6),  DATABASETIMESTAMP NUMBER(16,10),  DATABASETIMESTAMP_TZ NUMBER(6),  SEQUENCEID NUMBER(15),  STANDARDVALUE NUMBER(16,10),  USERNAMEFULL VARCHAR2(100), CONSTRAINT PKDATAITEMRESPONSE PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID, RESPONSETASKID, REPEATNUMBER));

CREATE TABLE DATAITEMRESPONSEHISTORY( CLINICALTRIALID NUMBER(11) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  PERSONID NUMBER(11) NOT NULL,  RESPONSETASKID NUMBER(11) NOT NULL,  RESPONSETIMESTAMP NUMBER(16,10) NOT NULL,  VISITID NUMBER(11),  CRFPAGEID NUMBER(11),  CRFELEMENTID NUMBER(6),  DATAITEMID NUMBER(11),  VISITCYCLENUMBER NUMBER(6),  CRFPAGECYCLENUMBER NUMBER(6),  CRFPAGETASKID NUMBER(11),  RESPONSEVALUE VARCHAR2(255),  VALUECODE VARCHAR2(15),  USERNAME VARCHAR2(20),  UNITOFMEASUREMENT VARCHAR2(15),  COMMENTS VARCHAR2(255),  RESPONSESTATUS NUMBER(6),  CHANGED NUMBER(6),  SOFTWAREVERSION VARCHAR2(15),  REASONFORCHANGE VARCHAR2(255),  LOCKSTATUS NUMBER(3),  IMPORTTIMESTAMP NUMBER(16,10),  VALIDATIONID NUMBER(6),  VALIDATIONMESSAGE VARCHAR2(4000),  OVERRULEREASON VARCHAR2(255),  LABRESULT VARCHAR2(1),  CTCGRADE NUMBER(6),  CLINICALTESTDATE NUMBER(16,10),  LABORATORYCODE VARCHAR2(15),  HADVALUE NUMBER(6),  REPEATNUMBER NUMBER(6) NOT NULL,  RESPONSETIMESTAMP_TZ NUMBER(6),  IMPORTTIMESTAMP_TZ NUMBER(6),  DATABASETIMESTAMP NUMBER(16,10),  DATABASETIMESTAMP_TZ NUMBER(6),  SEQUENCEID NUMBER(15),  STANDARDVALUE NUMBER(16,10),  USERNAMEFULL VARCHAR2(100), CONSTRAINT PKDATAITEMRESPONSEHISTORY PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID, RESPONSETASKID, RESPONSETIMESTAMP, REPEATNUMBER));

CREATE TABLE DATAITEMVALIDATION( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  DATAITEMID NUMBER(11) NOT NULL,  VALIDATIONID NUMBER(6) NOT NULL,  VALIDATIONTYPEID NUMBER(6),  DATAITEMVALIDATION VARCHAR2(4000),  VALIDATIONMESSAGE VARCHAR2(4000), CONSTRAINT PKDATAITEMVALIDATION PRIMARY KEY (CLINICALTRIALID, DATAITEMID, VALIDATIONID, VERSIONID));

CREATE TABLE DATATYPE( DATATYPEID NUMBER(11) NOT NULL,  DATATYPENAME VARCHAR2(15), CONSTRAINT PKDATATYPE PRIMARY KEY (DATATYPEID));

CREATE TABLE EFORMQGROUP( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  CRFPAGEID NUMBER(11) NOT NULL,  QGROUPID NUMBER(11) NOT NULL,  BORDER NUMBER(6),  DISPLAYROWS NUMBER(6),  INITIALROWS NUMBER(6),  MINREPEATS NUMBER(6),  MAXREPEATS NUMBER(6), CONSTRAINT PKEFORMQUESTIONGROUP PRIMARY KEY (CLINICALTRIALID, VERSIONID, CRFPAGEID, QGROUPID));

CREATE TABLE ELIGIBILITY( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  ELIGIBILITYCODE VARCHAR2(15) NOT NULL,  RANDOMISATIONCODE VARCHAR2(15),  FLAG NUMBER(6),  CONDITION VARCHAR2(4000), CONSTRAINT PKELIGIBILITY PRIMARY KEY (CLINICALTRIALID, ELIGIBILITYCODE, VERSIONID));

CREATE TABLE KEYWORD( KEYWORD VARCHAR2(50) NOT NULL, CONSTRAINT PKKEYWORD PRIMARY KEY (KEYWORD));

CREATE TABLE LFMESSAGE( CLINICALTRIALNAME VARCHAR2(15) NOT NULL,  CLINICALTRIALID NUMBER(11) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  PERSONID NUMBER(11) NOT NULL,  SOURCE NUMBER(6) NOT NULL,  MESSAGEID NUMBER(11) NOT NULL,  SCOPE NUMBER(6),  VISITID NUMBER(11),  VISITCYCLENUMBER NUMBER(6),  CRFPAGEID NUMBER(11),  CRFPAGECYCLENUMBER NUMBER(6),  RESPONSETASKID NUMBER(11),  REPEATNUMBER NUMBER(6),  DATAITEMID NUMBER(11),  USERNAME VARCHAR2(20),  USERNAMEFULL VARCHAR2(100),  MSGTYPE NUMBER(6),  ROLLBACKSOURCE NUMBER(6),  ROLLBACKMESSAGEID NUMBER(11),  PROCESSEDSTATUS NUMBER(6),  MSGCREATEDTIMESTAMP NUMBER(16,10),  MSGCREATEDTIMESTAMP_TZ NUMBER(6),  PROCESSEDTIMESTAMP NUMBER(16,10),  PROCESSEDTIMESTAMP_TZ NUMBER(6),  SENTTIMESTAMP NUMBER(16,10),  SENTTIMESTAMP_TZ NUMBER(6),  RECEIVEDTIMESTAMP NUMBER(16,10),  RECEIVEDTIMESTAMP_TZ NUMBER(6),  SEQUENCENO NUMBER(11), CONSTRAINT PKLFMESSAGE PRIMARY KEY (CLINICALTRIALNAME, CLINICALTRIALID, TRIALSITE, PERSONID, SOURCE, MESSAGEID));

CREATE TABLE LABORATORY( LABORATORYCODE VARCHAR2(15) NOT NULL,  LABORATORYDESCRIPTION VARCHAR2(255),  SITE VARCHAR2(8),  CHANGED NUMBER(6), CONSTRAINT PKLABORATORY PRIMARY KEY (LABORATORYCODE));

CREATE TABLE LOGDETAILS( LOGDATETIME NUMBER(16,10) NOT NULL,  LOGNUMBER NUMBER(11) NOT NULL,  TASKID VARCHAR2(50) NOT NULL,  LOGMESSAGE VARCHAR2(255),  USERNAME VARCHAR2(20),  LOGDATETIME_TZ NUMBER(6),  LOCATION VARCHAR2(50) NOT NULL,  STATUS NUMBER(6), CONSTRAINT PKLOGDETAILS PRIMARY KEY (LOGDATETIME, LOGNUMBER, TASKID, LOCATION));

CREATE TABLE MACROCONTROL( MACROVERSION VARCHAR2(15),  BUILDSUBVERSION VARCHAR2(10),  IDLETIMEOUT NUMBER(6));

CREATE TABLE MACROCOUNTRY( COUNTRYID NUMBER(6) NOT NULL,  COUNTRYDESCRIPTION VARCHAR2(50), CONSTRAINT PKMACROCOUNTRY PRIMARY KEY (COUNTRYID));

CREATE TABLE MACRODBSETTING( SETTINGSECTION VARCHAR2(15) NOT NULL,  SETTINGKEY VARCHAR2(15) NOT NULL,  SETTINGVALUE VARCHAR2(15), CONSTRAINT PKMACRODBSETTING PRIMARY KEY (SETTINGSECTION, SETTINGKEY));

CREATE TABLE MACROLOCK( STUDYID NUMBER(11) NOT NULL,  SITE VARCHAR2(8) NOT NULL,  SUBJECTID NUMBER(11) NOT NULL,  EFORMINSTANCEID NUMBER(11) NOT NULL,  USERNAME VARCHAR2(20),  LOCKTIMESTAMP NUMBER(16,10),  TOKEN VARCHAR2(10), CONSTRAINT PKMACROLOCK PRIMARY KEY (STUDYID, SITE, SUBJECTID, EFORMINSTANCEID));

CREATE TABLE MACROTABLE( TABLENAME VARCHAR2(30) NOT NULL,  SEGMENTID VARCHAR2(3),  STYDEF NUMBER(6),  PATRSP NUMBER(6),  LABDEF NUMBER(6), CONSTRAINT PKMACROTABLE PRIMARY KEY (TABLENAME));

CREATE TABLE MACROUSERSETTINGS( USERNAME VARCHAR2(20) NOT NULL,  USERSETTING VARCHAR2(20) NOT NULL,  SETTINGVALUE VARCHAR2(50) NOT NULL, CONSTRAINT PKMACROUSERSETTING PRIMARY KEY (USERNAME, USERSETTING, SETTINGVALUE));

CREATE TABLE MIMESSAGE( MIMESSAGEID NUMBER(11) NOT NULL,  MIMESSAGESITE VARCHAR2(8) NOT NULL,  MIMESSAGESOURCE NUMBER(6) NOT NULL,  MIMESSAGETYPE NUMBER(6),  MIMESSAGESCOPE NUMBER(6),  MIMESSAGEOBJECTID NUMBER(11),  MIMESSAGEOBJECTSOURCE NUMBER(6),  MIMESSAGEPRIORITY NUMBER(6),  MIMESSAGETRIALNAME VARCHAR2(15),  MIMESSAGEPERSONID NUMBER(11),  MIMESSAGEVISITID NUMBER(11),  MIMESSAGEVISITCYCLE NUMBER(6),  MIMESSAGECRFPAGETASKID NUMBER(11),  MIMESSAGERESPONSETASKID NUMBER(11),  MIMESSAGERESPONSEVALUE VARCHAR2(255),  MIMESSAGEOCDISCREPANCYID NUMBER(11),  MIMESSAGECREATED NUMBER(16,10),  MIMESSAGESENT NUMBER(16,10),  MIMESSAGERECEIVED NUMBER(16,10),  MIMESSAGEHISTORY NUMBER(6),  MIMESSAGEPROCESSED NUMBER(6),  MIMESSAGESTATUS NUMBER(6),  MIMESSAGETEXT VARCHAR2(2000),  MIMESSAGEUSERNAME VARCHAR2(20),  MIMESSAGEUSERNAMEFULL VARCHAR2(100),  MIMESSAGERESPONSETIMESTAMP NUMBER(16,10),  MIMESSAGERESPONSECYCLE NUMBER(6),  MIMESSAGECREATED_TZ NUMBER(6),  MIMESSAGESENT_TZ NUMBER(6),  MIMESSAGERECEIVED_TZ NUMBER(6),  SEQUENCEID NUMBER(15),  MIMESSAGECRFPAGEID NUMBER(11),  MIMESSAGECRFPAGECYCLE NUMBER(6),  MIMESSAGEDATAITEMID NUMBER(11), CONSTRAINT PKMIMESSAGE PRIMARY KEY (MIMESSAGEID, MIMESSAGESITE, MIMESSAGESOURCE));

CREATE TABLE MESSAGE( TRIALSITE VARCHAR2(8) NOT NULL,  CLINICALTRIALID NUMBER(11),  MESSAGETYPE NUMBER(6),  MESSAGETIMESTAMP NUMBER(16,10),  USERNAME VARCHAR2(20),  MESSAGEBODY VARCHAR2(255),  MESSAGEPARAMETERS VARCHAR2(3000),  MESSAGERECEIVED NUMBER(6),  MESSAGEDIRECTION NUMBER(6) NOT NULL,  MESSAGEID NUMBER(11) NOT NULL,  MESSAGERECEIVEDTIMESTAMP NUMBER(16,10),  MESSAGETIMESTAMP_TZ NUMBER(6),  MESSAGERECEIVEDTIMESTAMP_TZ NUMBER(6), CONSTRAINT PKMESSAGE PRIMARY KEY (TRIALSITE, MESSAGEID, MESSAGEDIRECTION));

CREATE TABLE NEWDBCOLUMN( VERSIONMAJOR NUMBER(6) NOT NULL,  VERSIONMINOR NUMBER(6) NOT NULL,  VERSIONREVISION NUMBER(6) NOT NULL,  TABLENAME VARCHAR2(30) NOT NULL,  COLUMNNAME VARCHAR2(30) NOT NULL,  COLUMNORDER NUMBER(6),  DEFAULTVALUE VARCHAR2(255),  CHANGETYPE VARCHAR2(15),  COLUMNNUMBER NUMBER(6), CONSTRAINT PKNEWDBCOLUMN PRIMARY KEY (VERSIONMAJOR, VERSIONMINOR, VERSIONREVISION, TABLENAME, COLUMNNAME));

CREATE TABLE NORMALRANGE( NORMALRANGEID NUMBER(11) NOT NULL,  LABORATORYCODE VARCHAR2(15) NOT NULL,  CLINICALTESTCODE VARCHAR2(15),  NORMALRANGEGENDER NUMBER(6),  NORMALRANGEAGEMIN NUMBER(6),  NORMALRANGEAGEMAX NUMBER(6),  NORMALRANGEEFFECTIVESTART NUMBER(16,10),  NORMALRANGEEFFECTIVEEND NUMBER(16,10),  NORMALRANGENORMALMIN NUMBER(16,10),  NORMALRANGENORMALMAX NUMBER(16,10),  NORMALRANGEFEASIBLEMIN NUMBER(16,10),  NORMALRANGEFEASIBLEMAX NUMBER(16,10),  NORMALRANGEABSOLUTEMIN NUMBER(16,10),  NORMALRANGEABSOLUTEMAX NUMBER(16,10),  NORMALRANGEPERCENT NUMBER(6), CONSTRAINT PKNORMALRANGE PRIMARY KEY (LABORATORYCODE, NORMALRANGEID));

CREATE TABLE PROTOCOLS( FILENAME VARCHAR2(50) NOT NULL,  PROTOCOLNAME VARCHAR2(50),  VERSION VARCHAR2(50),  DESCRIPTION VARCHAR2(2000),  AUTHOR VARCHAR2(50),  CREATED NUMBER(16,10),  MODIFIED NUMBER(16,10),  AREZZOVERSION VARCHAR2(50),  INUSE NUMBER(6),  AREZZOFILE LONG, CONSTRAINT PKPROTOCOLS PRIMARY KEY (FILENAME));

CREATE TABLE QGROUP( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  QGROUPID NUMBER(11) NOT NULL,  QGROUPCODE VARCHAR2(15),  QGROUPNAME VARCHAR2(255),  DISPLAYTYPE NUMBER(6), CONSTRAINT PKQGROUP PRIMARY KEY (CLINICALTRIALID, VERSIONID, QGROUPID));

CREATE TABLE QGROUPQUESTION( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  QGROUPID NUMBER(11) NOT NULL,  DATAITEMID NUMBER(11) NOT NULL,  QORDER NUMBER(6), CONSTRAINT PKQGROUPQUESTION PRIMARY KEY (CLINICALTRIALID, VERSIONID, QGROUPID, DATAITEMID));

CREATE TABLE RSNEXTNUMBER( CLINICALTRIALNAME VARCHAR2(15) NOT NULL,  NEXTNUMBERID NUMBER(11) NOT NULL,  PREFIX VARCHAR2(255),  SUFFIX VARCHAR2(255),  NEXTNUMBER NUMBER(11), CONSTRAINT PKRSNEXTNUMBER PRIMARY KEY (CLINICALTRIALNAME, NEXTNUMBERID));

CREATE TABLE RSSUBJECTIDENTIFIER( CLINICALTRIALNAME VARCHAR2(15) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  PERSONID NUMBER(11) NOT NULL,  SUBJECTIDENTIFIER VARCHAR2(255), CONSTRAINT PKRSSUBJECTIDENTIFIER PRIMARY KEY (CLINICALTRIALNAME, TRIALSITE, PERSONID));

CREATE TABLE RSUNIQUENESSCHECK( CLINICALTRIALNAME VARCHAR2(15) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  PERSONID NUMBER(11) NOT NULL,  CHECKCODE VARCHAR2(15) NOT NULL,  CHECKVALUE VARCHAR2(255),  CHECKTIMESTAMP NUMBER(16,10),  CHECKTIMESTAMP_TZ NUMBER(6), CONSTRAINT PKRSUNIQUENESSCHECK PRIMARY KEY (CLINICALTRIALNAME, TRIALSITE, PERSONID, CHECKCODE));

CREATE TABLE REASONFORCHANGE( CLINICALTRIALID NUMBER(11),  VERSIONID NUMBER(6),  REASONFORCHANGEID NUMBER(6),  REASONFORCHANGE VARCHAR2(255),  REASONTYPE NUMBER(6));

CREATE TABLE REQUIREDDATA( DATAITEMID NUMBER(11) NOT NULL,  TRIALTYPEID NUMBER(6) NOT NULL, CONSTRAINT PKREQUIREDDATA PRIMARY KEY (DATAITEMID, TRIALTYPEID));

CREATE TABLE SITE( SITE VARCHAR2(8) NOT NULL,  SITEDESCRIPTION VARCHAR2(255),  SITESTATUS NUMBER(6),  SITELOCATION NUMBER(6),  SITECOUNTRY NUMBER(6), CONSTRAINT PKSITE PRIMARY KEY (SITE));

CREATE TABLE SITELABORATORY( SITE VARCHAR2(8) NOT NULL,  LABORATORYCODE VARCHAR2(15) NOT NULL, CONSTRAINT PKSITELABORATORY PRIMARY KEY (SITE, LABORATORYCODE));

CREATE TABLE STANDARDDATAFORMAT( STANDARDDATAFORMATID NUMBER(6) NOT NULL,  DATAFORMAT VARCHAR2(255),  DATATYPEID NUMBER(6), CONSTRAINT PKSTANDARDDATAFORMAT PRIMARY KEY (STANDARDDATAFORMATID));

CREATE TABLE STUDYDEFINITION( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  DEFAULTFONTCOLOUR NUMBER(11),  DEFAULTCRFPAGECOLOUR NUMBER(11),  DEFAULTFONTNAME VARCHAR2(50),  DEFAULTFONTBOLD NUMBER(6),  DEFAULTFONTITALIC NUMBER(6),  DEFAULTFONTSIZE NUMBER(6),  USERNAME VARCHAR2(20),  STUDYDEFINITIONTIMESTAMP NUMBER(16,10),  TRIALSUBJECTLABEL VARCHAR2(255),  LOCALTRIALSUBJECTLABEL NUMBER(6),  STANDARDDATEFORMAT VARCHAR2(50),  STANDARDTIMEFORMAT VARCHAR2(50),  SINGLEUSEDATAITEMS NUMBER(6),  CTCSCHEMECODE VARCHAR2(15),  DOBEXPR VARCHAR2(4000),  GENDEREXPR VARCHAR2(4000),  RRSERVERTYPE NUMBER(6),  RRHTTPADDRESS VARCHAR2(255),  RRUSERNAME VARCHAR2(20),  RRPASSWORD VARCHAR2(50),  RRPROXYSERVER VARCHAR2(255),  AREZZOUPDATESTATUS NUMBER(6),  AREZZOMEMORY VARCHAR2(100), CONSTRAINT PKSTUDYDEFINITION PRIMARY KEY (CLINICALTRIALID, VERSIONID));

CREATE TABLE STUDYDOCUMENT( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  DOCUMENTID NUMBER(6) NOT NULL,  DOCUMENTPATH VARCHAR2(255), CONSTRAINT PKSTUDYDOCUMENT PRIMARY KEY (CLINICALTRIALID, DOCUMENTID, VERSIONID));

CREATE TABLE STUDYREPORT( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  REPORTID NUMBER(6) NOT NULL,  REPORTNAME VARCHAR2(255),  REPORTTYPE NUMBER(6),  AUTOMATICNUMBERING NUMBER(6), CONSTRAINT PKSTUDYREPORT PRIMARY KEY (CLINICALTRIALID, REPORTID, VERSIONID));

CREATE TABLE STUDYREPORTDATA( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  REPORTID NUMBER(6) NOT NULL,  REPORTLINEID NUMBER(6) NOT NULL,  SEGMENTID NUMBER(11) NOT NULL,  SEQUENCENUMBER NUMBER(11),  VISITID NUMBER(11),  CRFPAGEID NUMBER(11),  DATAITEMID NUMBER(11),  CRFELEMENTID NUMBER(6),  SEGMENTTEXT VARCHAR2(255), CONSTRAINT PKSTUDYREPORTDATA PRIMARY KEY (CLINICALTRIALID, REPORTID, REPORTLINEID, SEGMENTID, VERSIONID));

CREATE TABLE STUDYVERSION( CLINICALTRIALID NUMBER(11) NOT NULL,  STUDYVERSION NUMBER(6) NOT NULL,  VERSIONTIMESTAMP NUMBER(16,10),  VERSIONDESCRIPTION VARCHAR2(255),  VERSIONTIMESTAMP_TZ NUMBER(6), CONSTRAINT PKSTUDYVERSION PRIMARY KEY (CLINICALTRIALID, STUDYVERSION));

CREATE TABLE STUDYVISIT( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  VISITID NUMBER(11) NOT NULL,  VISITNAME VARCHAR2(50),  VISITORDER NUMBER(6),  VISITCODE VARCHAR2(15),  VISITDATELABEL VARCHAR2(255),  VISITBACKGROUNDCOLOUR NUMBER(11),  VISITDATEPROMPT NUMBER(3),  REPEATING NUMBER(6), CONSTRAINT PKSTUDYVISIT PRIMARY KEY (CLINICALTRIALID, VISITID, VERSIONID));

CREATE TABLE STUDYVISITCRFPAGE( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  VISITID NUMBER(11) NOT NULL,  CRFPAGEID NUMBER(11) NOT NULL,  REPEATING NUMBER(6),  EFORMUSE NUMBER(6), CONSTRAINT PKSTUDYVISITCRFPAGE PRIMARY KEY (CLINICALTRIALID, VISITID, CRFPAGEID, VERSIONID));

CREATE TABLE SUBJECTNUMBERING( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  STARTNUMBER NUMBER(11),  NUMBERWIDTH NUMBER(6),  PREFIX VARCHAR2(4000),  USEPREFIX NUMBER(6),  SUFFIX VARCHAR2(4000),  USESUFFIX NUMBER(6),  TRIGGERVISITID NUMBER(11),  TRIGGERFORMID NUMBER(11),  USEREGISTRATION NUMBER(6), CONSTRAINT PKSUBJECTNUMBERING PRIMARY KEY (CLINICALTRIALID, VERSIONID));

CREATE TABLE TRIALOFFICE( TRIALOFFICE VARCHAR2(50) NOT NULL,  EFFECTIVEFROM NUMBER(16,10) NOT NULL,  EFFECTIVETO NUMBER(16,10) NOT NULL,  HTTPADDRESS VARCHAR2(255),  SITE VARCHAR2(8),  TRANSFERDATA NUMBER(6),  USERNAME VARCHAR2(50),  USERPASSWORD VARCHAR2(50),  PORTNUMBER NUMBER(6),  PROXYSERVER VARCHAR2(255), CONSTRAINT PKTRIALOFFICE PRIMARY KEY (TRIALOFFICE, EFFECTIVEFROM, EFFECTIVETO));

CREATE TABLE TRIALPHASE( PHASEID NUMBER(6) NOT NULL,  PHASENAME VARCHAR2(50), CONSTRAINT PKTRIALPHASE PRIMARY KEY (PHASEID));

CREATE TABLE TRIALSITE( CLINICALTRIALID NUMBER(11) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  STUDYVERSION NUMBER(6), CONSTRAINT PKTRIALSITE PRIMARY KEY (CLINICALTRIALID, TRIALSITE));

CREATE TABLE TRIALSTATUS( STATUSID NUMBER(6) NOT NULL,  STATUSNAME VARCHAR2(50), CONSTRAINT PKTRIALSTATUS PRIMARY KEY (STATUSID));

CREATE TABLE TRIALSTATUSHISTORY( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  TRIALSTATUSCHANGEID NUMBER(6) NOT NULL,  STATUSID NUMBER(6),  USERNAME VARCHAR2(20),  STATUSCHANGEDTIMESTAMP NUMBER(16,10),  STATUSCHANGEDTIMESTAMP_TZ NUMBER(6), CONSTRAINT PKTRIALSTATUSHISTORY PRIMARY KEY (CLINICALTRIALID, TRIALSTATUSCHANGEID, VERSIONID));

CREATE TABLE TRIALSUBJECT( CLINICALTRIALID NUMBER(11) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  PERSONID NUMBER(11) NOT NULL,  DATEOFBIRTH NUMBER(16,10),  GENDER VARCHAR2(1),  LOCALIDENTIFIER1 VARCHAR2(50),  LOCALIDENTIFIER2 VARCHAR2(50),  PROFORMASTATE LONG,  TRIALSUBJECTSTATUS NUMBER(6),  CHANGED NUMBER(6),  LOCKSTATUS NUMBER(3),  IMPORTTIMESTAMP NUMBER(16,10),  SUBJECTGENDER NUMBER(6),  REGISTRATIONSTATUS NUMBER(6),  DISCREPANCYSTATUS NUMBER(6),  SDVSTATUS NUMBER(6),  NOTESTATUS NUMBER(6),  IMPORTTIMESTAMP_TZ NUMBER(6),  SEQUENCEID NUMBER(15),  SUBJECTTIMESTAMP NUMBER(16,10),  SUBJECTTIMESTAMP_TZ NUMBER(6), CONSTRAINT PKTRIALSUBJECT PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID));

CREATE TABLE TRIALTYPE( TRIALTYPEID NUMBER(6) NOT NULL,  TRIALTYPENAME VARCHAR2(50), CONSTRAINT PKTRIALTYPE PRIMARY KEY (TRIALTYPEID));

CREATE TABLE UNIQUENESSCHECK( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  CHECKCODE VARCHAR2(15) NOT NULL,  EXPRESSION VARCHAR2(4000), CONSTRAINT PKUNIQUENESSCHECK PRIMARY KEY (CLINICALTRIALID, CHECKCODE, VERSIONID));

CREATE TABLE UNITCLASSES( UNITCLASS VARCHAR2(50) NOT NULL, CONSTRAINT PKUNITCLASSES PRIMARY KEY (UNITCLASS));

CREATE TABLE UNITCONVERSIONFACTORS( FROMUNIT VARCHAR2(15) NOT NULL,  TOUNIT VARCHAR2(15) NOT NULL,  CONVERSIONFACTOR NUMBER(16,10),  UNITCLASS VARCHAR2(50), CONSTRAINT PKUNITCONVERSIONFACTORS PRIMARY KEY (FROMUNIT, TOUNIT));

CREATE TABLE UNITS( UNIT VARCHAR2(15) NOT NULL,  UNITCLASS VARCHAR2(50), CONSTRAINT PKUNITS PRIMARY KEY (UNIT));

CREATE TABLE USERROLE( USERNAME VARCHAR2(20) NOT NULL,  ROLECODE VARCHAR2(15) NOT NULL,  STUDYCODE VARCHAR2(50) NOT NULL,  SITECODE VARCHAR2(50) NOT NULL,  TYPEOFINSTALLATION NUMBER(6) NOT NULL, CONSTRAINT PKUSERROLE PRIMARY KEY (USERNAME, ROLECODE, STUDYCODE, SITECODE, TYPEOFINSTALLATION));

CREATE TABLE VALIDATIONACTION( VALIDATIONACTIONID NUMBER(6) NOT NULL,  VALIDATIONACTIONNAME VARCHAR2(15), CONSTRAINT PKVALIDATIONACTION PRIMARY KEY (VALIDATIONACTIONID));

CREATE TABLE VALIDATIONTYPE( VALIDATIONTYPEID NUMBER(6) NOT NULL,  VALIDATIONTYPENAME VARCHAR2(50),  VALIDATIONACTIONID NUMBER(6), CONSTRAINT PKVALIDATIONTYPE PRIMARY KEY (VALIDATIONTYPEID));

CREATE TABLE VALUEDATA( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  DATAITEMID NUMBER(11) NOT NULL,  VALUEID NUMBER(6) NOT NULL,  VALUECODE VARCHAR2(15),  ITEMVALUE VARCHAR2(255),  ACTIVE NUMBER(6),  VALUEORDER NUMBER(6), CONSTRAINT PKVALUEDATA PRIMARY KEY (CLINICALTRIALID, DATAITEMID, VALUEID, VERSIONID));

CREATE TABLE VISITINSTANCE( CLINICALTRIALID NUMBER(11) NOT NULL,  TRIALSITE VARCHAR2(8) NOT NULL,  PERSONID NUMBER(11) NOT NULL,  VISITTASKID NUMBER(11) NOT NULL,  VISITID NUMBER(11),  VISITCYCLENUMBER NUMBER(6),  VISITDATE NUMBER(16,10),  VISITSTATUS NUMBER(6),  CHANGED NUMBER(6),  LOCKSTATUS NUMBER(3),  IMPORTTIMESTAMP NUMBER(16,10),  DISCREPANCYSTATUS NUMBER(6),  SDVSTATUS NUMBER(6),  NOTESTATUS NUMBER(6),  IMPORTTIMESTAMP_TZ NUMBER(6),  SEQUENCEID NUMBER(15), CONSTRAINT PKVISITINSTANCE PRIMARY KEY (CLINICALTRIALID, TRIALSITE, PERSONID, VISITTASKID));


