CREATE TABLE DATABASES( DATABASECODE VARCHAR2(15) NOT NULL,  HTMLLOCATION VARCHAR2(255),  DATABASELOCATION VARCHAR2(255),  DATABASETYPE NUMBER(6),  SERVERNAME VARCHAR2(50),  NAMEOFDATABASE VARCHAR2(50),  DATABASEUSER VARCHAR2(100),  DATABASEPASSWORD VARCHAR2(100),  SECUREHTMLLOCATION VARCHAR2(255),  REPORTSLOCATION VARCHAR2(255), CONSTRAINT PKDATABASES PRIMARY KEY (DATABASECODE));

CREATE TABLE MACROFUNCTION( FUNCTIONCODE VARCHAR2(15) NOT NULL,  MACROFUNCTION VARCHAR2(255), CONSTRAINT PKMACROFUNCTION PRIMARY KEY (FUNCTIONCODE));

CREATE TABLE LOGINLOG( LOGDATETIME NUMBER(16,10) NOT NULL,  LOGNUMBER NUMBER(11) NOT NULL,  TASKID VARCHAR2(50) NOT NULL,  LOGMESSAGE VARCHAR2(255),  USERNAME VARCHAR2(20),  LOGDATETIME_TZ NUMBER(6),  LOCATION VARCHAR2(50) NOT NULL,  STATUS NUMBER(6), CONSTRAINT PKLOGINLOG PRIMARY KEY (LOGDATETIME, LOGNUMBER, TASKID, LOCATION));

CREATE TABLE MACROPASSWORD( MINLENGTH NUMBER(6),  MAXLENGTH NUMBER(6),  EXPIRYPERIOD NUMBER(6),  ENFORCEMIXEDCASE NUMBER(6),  ENFORCEDIGIT NUMBER(6),  ALLOWREPEATCHARS NUMBER(6),  ALLOWUSERNAME NUMBER(6),  PASSWORDHISTORY NUMBER(6),  PASSWORDRETRIES NUMBER(6));

CREATE TABLE MACROUSER( USERNAME VARCHAR2(20) NOT NULL,  USERNAMEFULL VARCHAR2(100),  USERPASSWORD VARCHAR2(100),  ENABLED NUMBER(6),  LASTLOGIN NUMBER(16,10),  FIRSTLOGIN NUMBER(16,10),  DEFAULTUSERROLECODE VARCHAR2(15),  FAILEDATTEMPTS NUMBER(6),  PASSWORDCREATED NUMBER(16,10),  SYSADMIN NUMBER(6), CONSTRAINT PKMACROUSER PRIMARY KEY (USERNAME));

CREATE TABLE ONLINESUPPORT( SUPPORTUSERNAME VARCHAR2(50),  SUPPORTUSERPASSWORD VARCHAR2(50),  SUPPORTURL VARCHAR2(255));

CREATE TABLE PASSWORDHISTORY( USERNAME VARCHAR2(20) NOT NULL,  HISTORYNUMBER NUMBER(6) NOT NULL,  PASSWORDCREATED NUMBER(16,10),  USERPASSWORD VARCHAR2(100), CONSTRAINT PKPASSWORDHISTORY PRIMARY KEY (USERNAME, HISTORYNUMBER));

CREATE TABLE ROLE( ROLECODE VARCHAR2(15) NOT NULL,  ROLEDESCRIPTION VARCHAR2(255),  ENABLED NUMBER(6),  SYSADMIN NUMBER(6), CONSTRAINT PKROLE PRIMARY KEY (ROLECODE));

CREATE TABLE ROLEFUNCTION( ROLECODE VARCHAR2(15) NOT NULL,  FUNCTIONCODE VARCHAR2(15) NOT NULL, CONSTRAINT PKROLEFUNCTION PRIMARY KEY (ROLECODE, FUNCTIONCODE));

CREATE TABLE SECURITYCONTROL( SECURITYMODE NUMBER(11),  MACROVERSION VARCHAR2(15),  BUILDSUBVERSION VARCHAR2(5));

CREATE TABLE USERDATABASE( USERNAME VARCHAR2(20) NOT NULL,  DATABASECODE VARCHAR2(15) NOT NULL, CONSTRAINT PKUSERDATABASE PRIMARY KEY (USERNAME, DATABASECODE));

CREATE TABLE FUNCTIONMODULE( FUNCTIONCODE VARCHAR2(15) NOT NULL,  MACROMODULE VARCHAR2(15) NOT NULL);


