

CREATE TABLE TEMPCRFELEMENT( CLINICALTRIALID NUMBER(11) NOT NULL,  VERSIONID NUMBER(6) NOT NULL,  CRFPAGEID NUMBER(11) NOT NULL,  CRFELEMENTID NUMBER(6) NOT NULL,  DATAITEMID NUMBER(11),  CONTROLTYPE NUMBER(6),  FONTCOLOUR NUMBER(11),  CAPTION VARCHAR2(255),  FONTNAME VARCHAR2(50),  FONTBOLD NUMBER(6),  FONTITALIC NUMBER(6),  FONTSIZE NUMBER(6),  FIELDORDER NUMBER(6),  SKIPCONDITION VARCHAR2(4000),  HEIGHT NUMBER(6),  WIDTH NUMBER(6),  CAPTIONX NUMBER(11),  CAPTIONY NUMBER(11),  X NUMBER(11),  Y NUMBER(11),  PRINTORDER NUMBER(11),  HIDDEN NUMBER(6),  LOCALFLAG NUMBER(6),  OPTIONAL NUMBER(6),  MANDATORY NUMBER(6),  REQUIRECOMMENT NUMBER(6),  ROLECODE VARCHAR2(15),  CLINICALTESTDATEEXPR VARCHAR2(2000),  OWNERQGROUPID NUMBER(11),  QGROUPID NUMBER(11),  QGROUPFIELDORDER NUMBER(6),  SHOWSTATUSFLAG NUMBER(6),  CAPTIONFONTNAME VARCHAR2(50),  CAPTIONFONTBOLD NUMBER(6),  CAPTIONFONTITALIC NUMBER(6),  CAPTIONFONTSIZE NUMBER(6),  CAPTIONFONTCOLOUR NUMBER(11),  ELEMENTUSE NUMBER(6),  DISPLAYLENGTH NUMBER(6),  HOTLINK VARCHAR2(2000),  DESCRIPTION VARCHAR2(255));

INSERT INTO TEMPCRFELEMENT SELECT CLINICALTRIALID,VERSIONID, CRFPAGEID, CRFELEMENTID, DATAITEMID, CONTROLTYPE, FONTCOLOUR, CAPTION, FONTNAME, FONTBOLD, FONTITALIC, FONTSIZE, FIELDORDER, SKIPCONDITION, HEIGHT,WIDTH, CAPTIONX,CAPTIONY, X,Y, PRINTORDER, HIDDEN,LOCALFLAG,OPTIONAL,MANDATORY, REQUIRECOMMENT, ROLECODE, CLINICALTESTDATEEXPR,  OWNERQGROUPID,QGROUPID,QGROUPFIELDORDER, SHOWSTATUSFLAG, CAPTIONFONTNAME, CAPTIONFONTBOLD, CAPTIONFONTITALIC, CAPTIONFONTSIZE, CAPTIONFONTCOLOUR, ELEMENTUSE, DISPLAYLENGTH, HOTLINK, DESCRIPTION FROM CRFELEMENT;

DROP TABLE CRFELEMENT;

RENAME TEMPCRFELEMENT TO CRFELEMENT;

ALTER TABLE CRFELEMENT ADD CONSTRAINT PKCRFELEMENT PRIMARY KEY (CLINICALTRIALID, CRFPAGEID, CRFELEMENTID, VERSIONID);

