DROP INDEX MESSAGE.IDX_MES_TRIALSITE;
ALTER TABLE MESSAGE ALTER COLUMN TRIALSITE VARCHAR(8) NOT NULL;
ALTER TABLE MESSAGE ALTER COLUMN MESSAGEDIRECTION SMALLINT NOT NULL;
ALTER TABLE MESSAGE DROP CONSTRAINT PKMESSAGE;
ALTER TABLE MESSAGE ADD CONSTRAINT PKMESSAGE PRIMARY KEY (TRIALSITE, MESSAGEID, MESSAGEDIRECTION);
ALTER TABLE MESSAGE ALTER COLUMN MESSAGEPARAMETERS VARCHAR(2000);
CREATE  INDEX IDX_MES_TRIALSITE ON MESSAGE(TRIALSITE);

ALTER TABLE LOGDETAILS ADD STATUS SMALLINT;
GO
UPDATE LOGDETAILS SET STATUS = 0 WHERE STATUS IS NULL;
ALTER TABLE LOGDETAILS ALTER COLUMN LOCATION VARCHAR(50) NOT NULL;
ALTER TABLE LOGDETAILS DROP CONSTRAINT PKLOGDETIALS;
ALTER TABLE LOGDETAILS ADD CONSTRAINT PKLOGDETAILS PRIMARY KEY (LOGDATETIME, LOGNUMBER, TASKID, LOCATION);

INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES  (3,0,24,'LOGDETAILS','STATUS',1,'#NULL#','NEWCOLUMN',NULL);

UPDATE MACROControl SET BUILDSUBVERSION = '24';








