CREATE TABLE MACROUSERSETTINGS( USERNAME VARCHAR(15) NOT NULL,  USERSETTING VARCHAR(20) NOT NULL,  SETTINGVALUE VARCHAR(50), CONSTRAINT PKMACROUSERSETTING PRIMARY KEY (USERNAME, USERSETTING, SETTINGVALUE));
GO
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('MACROUSERSETTINGS','',0,0,0);

UPDATE MACROControl SET BUILDSUBVERSION = '26';








