CREATE TABLE DATAIMPORT( CLINICALTRIALNAME VARCHAR(15) NOT NULL, TRIALSITE VARCHAR(8) NOT NULL, PERSONID INT NOT NULL, DATAFILENAME VARCHAR(255), LASTLFMESSAGEID INT, RECEIVEDTIMESTAMP DECIMAL(16,10), RECEIVEDTIMESTAMP_TZ SMALLINT, CONSTRAINT PKDATAIMPORT PRIMARY KEY (CLINICALTRIALNAME, TRIALSITE, PERSONID, DATAFILENAME));
GO
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('LFMESSAGE','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('DATAIMPORT','',0,0,0);
UPDATE MACROControl SET BUILDSUBVERSION = '29';