ALTER TABLE MIMESSAGE ADD MIMESSAGECRFPAGEID INT;
ALTER TABLE MIMESSAGE ADD MIMESSAGECRFPAGECYCLE INT;
ALTER TABLE MIMESSAGE ADD MIMESSAGEDATAITEMID INT;

ALTER TABLE MIMESSAGE ALTER COLUMN MIMESSAGETEXT VARCHAR(2000);
GO
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,23,'MIMESSAGE','MIMESSAGECRFPAGEID',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,23,'MIMESSAGE','MIMESSAGECRFPAGECYCLE',null,'#NULL#','NEWCOLUMN',null);
INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES (3,0,23,'MIMESSAGE','MIMESSAGEDATAITEMID',null,'#NULL#','NEWCOLUMN',null);

UPDATE MIMESSAGE SET MIMESSAGEDATAITEMID = DATAITEMRESPONSE.DATAITEMID  FROM DATAITEMRESPONSE,CLINICALTRIAL WHERE CLINICALTRIAL.CLINICALTRIALID = DATAITEMRESPONSE.CLINICALTRIALID AND CLINICALTRIAL.CLINICALTRIALNAME = MIMESSAGE.MIMESSAGETRIALNAME  AND DATAITEMRESPONSE.TRIALSITE = MIMESSAGE.MIMESSAGESITE AND DATAITEMRESPONSE.PERSONID = MIMESSAGE.MIMESSAGEPERSONID AND DATAITEMRESPONSE.RESPONSETASKID = MIMESSAGE.MIMESSAGERESPONSETASKID;

UPDATE MIMESSAGE SET MIMESSAGECRFPAGEID = DATAITEMRESPONSE.CRFPAGEID, MIMESSAGECRFPAGECYCLE = DATAITEMRESPONSE.CRFPAGECYCLENUMBER FROM DATAITEMRESPONSE, CLINICALTRIAL WHERE CLINICALTRIAL.CLINICALTRIALID = DATAITEMRESPONSE.CLINICALTRIALID AND CLINICALTRIAL.CLINICALTRIALNAME = MIMESSAGE.MIMESSAGETRIALNAME AND DATAITEMRESPONSE.TRIALSITE = MIMESSAGE.MIMESSAGESITE AND DATAITEMRESPONSE.PERSONID = MIMESSAGE.MIMESSAGEPERSONID AND DATAITEMRESPONSE.RESPONSETASKID = MIMESSAGE.MIMESSAGERESPONSETASKID;


UPDATE MACROControl SET BUILDSUBVERSION = '23';