ALTER TABLE CRFELEMENT MODIFY(SKIPCONDITION VARCHAR2(4000));
ALTER TABLE DATAITEM MODIFY(DERIVATION VARCHAR2(4000));
ALTER TABLE DATAITEMRESPONSE MODIFY(VALIDATIONMESSAGE VARCHAR2(4000));
ALTER TABLE DATAITEMRESPONSEHISTORY MODIFY(VALIDATIONMESSAGE VARCHAR2(4000));
ALTER TABLE DATAITEMVALIDATION MODIFY(DATAITEMVALIDATION VARCHAR2(4000));
ALTER TABLE DATAITEMVALIDATION MODIFY(VALIDATIONMESSAGE VARCHAR2(4000));
ALTER TABLE ELIGIBILITY MODIFY(CONDITION VARCHAR2(4000));
ALTER TABLE STUDYDEFINITION MODIFY(DOBEXPR VARCHAR2(4000));
ALTER TABLE STUDYDEFINITION MODIFY(GENDEREXPR VARCHAR2(4000));
ALTER TABLE SUBJECTNUMBERING MODIFY(PREFIX VARCHAR2(4000));
ALTER TABLE SUBJECTNUMBERING MODIFY(SUFFIX VARCHAR2(4000));
ALTER TABLE UNIQUENESSCHECK MODIFY(EXPRESSION VARCHAR2(4000));
ALTER TABLE MACROUSERSETTINGS MODIFY(USERNAME VARCHAR2(20));

UPDATE MACROCONTROL SET BUILDSUBVERSION = '43';