CREATE TABLE DATAIMPORT( CLINICALTRIALNAME VARCHAR2(15) NOT NULL, TRIALSITE VARCHAR2(8) NOT NULL, PERSONID NUMBER(11) NOT NULL, DATAFILENAME VARCHAR2(255), LASTLFMESSAGEID NUMBER(11), RECEIVEDTIMESTAMP NUMBER(16,10), RECEIVEDTIMESTAMP_TZ NUMBER(6), CONSTRAINT PKDATAIMPORT PRIMARY KEY (CLINICALTRIALNAME, TRIALSITE, PERSONID, DATAFILENAME));

INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('LFMESSAGE','',0,0,0);
INSERT INTO MACROTable (TableName,SegmentId,STYDEF,PATRSP,LABDEF) VALUES ('DATAIMPORT','',0,0,0);

UPDATE MACROControl SET BUILDSUBVERSION = '29';
