ALTER TABLE MESSAGE DROP CONSTRAINT PKMESSAGE;
ALTER TABLE MESSAGE ADD CONSTRAINT PKMESSAGE PRIMARY KEY (TRIALSITE, MESSAGEID, MESSAGEDIRECTION);
ALTER TABLE MESSAGE MODIFY MESSAGEPARAMETERS VARCHAR2(2000);

ALTER TABLE LOGDETAILS ADD STATUS NUMBER(6);
UPDATE LOGDETAILS SET STATUS = 0 WHERE STATUS IS NULL;
ALTER TABLE LOGDETAILS DROP CONSTRAINT PKLOGDETIALS;
ALTER TABLE LOGDETAILS ADD CONSTRAINT PKLOGDETAILS PRIMARY KEY (LOGDATETIME, LOGNUMBER, TASKID, LOCATION);

INSERT INTO NewDBColumn (VersionMajor,VersionMinor,VersionRevision,TableName,ColumnName,ColumnOrder,DefaultValue,ChangeType,ColumnNumber) VALUES  (3,0,24,'LOGDETAILS','STATUS',1,'#NULL#','NEWCOLUMN',NULL);

UPDATE MACROControl SET BUILDSUBVERSION = '24';








