UPDATE ROLE SET ROLECODE = 'MACROUser' WHERE ROLECODE = 'MacroUser';
UPDATE ROLEFUNCTION SET ROLECODE = 'MACROUser' WHERE ROLECODE = 'MacroUser';

UPDATE SECURITYControl SET BUILDSUBVERSION = '25';








